init phone register:
    define "Literature Club":
        add "m" add "n" add "s" add "y"
        key "lit_club" as lit_club
    
    time day 1 month 10 year 2017 hour 12 minute 22
    "s" "Hihihi!"
    "n" "Oh? This for the club?"
    "m" "It is! Now we can update everyone on movements, if we’re going to be late, and so on."
    "m" "And just for organising things!"
    "y" "I can see the positives, yes"
    "y" "Are there plans for tomorrow evening, then?"
    "m" "There are! How would we feel about some speed reading?"
    "y" "Speed reading?"
    "s" "It’s where you read real fast!"
    "y" "No, I’m aware of what the words mean, Sayori"
    "s" "Oh"
    "n" "Please, you think you can pull a fast one on Sayori? She knows you had no idea~"
    "s" "Ehe~"
    "y" "But"
    "y" "Perhaps I didn’t, after all"
    "m" "Either way, yes, that’s the goal, to absorb as much as possible while taking the shortest amount of time we can."
    "m" "Everyone in?"
    "s" "Yep!"
    "n" "I mean, I’ll be there"
    "y" "I’ll do my best."
    "m" "Then let the game begin~"

    time day 3 hour 17 minute 55
    "m" "How would we feel about bringing in a new member this week?"
    "s" "Ooh! Who?"
    "m" "One of my friends from the grade below us expressed interest, so I was going to have her come along sometime."
    "n" "I don’t really feel either way about it, so that’s fine"
    "y" "I see"
    "m" "She’s a little quiet, but pretty dedicated. I’ll ask if she wants to come on Friday."
    "s" "Go for it! The more, the merrier!" 

    time day 6 hour 17 minute 11
    "s" "So this new girl, Ayaka? I dunno if she had a very good time..."
    "n" "I mean, we tried to make her feel welcome, but"
    "n" "You mighta smothered her a little"
    "s" "I didn’t mean to! She just seemed kinda lonely!"
    "n" "I don’t think it’s that bad, we’ll just see what she says tomorrow."
    "y" "I see"
    "n" "Also, I kinda thought it went without saying to not have any arguments, Yuri"
    "n" "If anything, that’s the reason she’s going to not come back"
    "s" "Natsuki"
    "y" "There wouldn’t have needed to be any sort of argument if you’d just backed down."
    "n" "I did! I kept my head down! I did what I could to be welcoming! You were just a colossal bitch the whole time!"
    "s" "Natsuki!"
    "n" "Seriously, what were you thinking?!"
    "y" "I kept to myself and stayed quiet, right up until you made a jab at me! It’s hardly fair to blame me for this!"
    "n" "I asked if you wanted to join the conversation! There was no jab, you psycho!"
    "n" "Fucking hell, you’re infuriating!"
    "s" "Both of you! Please!"
    "s" "Is this really what you want Monika to walk out of cram school to see?"
    "s" "None of us did well, we all admit that!"
    "s" "If she comes back, we’ll welcome her and be on our best behaviour, okay?"
    "s" "If not, we’ve potentially damaged one of Monika’s friendships!"
    "s" "That’s not cool!"
    "y" "No, you’re right. We’re all at fault here."
    "n" "Me? I didn’t do anything."
    "s" "Natsuki, please!"
    "n" "Fine. But only because you asked me to."
    "y" "Whipped bitch."
    "n" "You want to fucking go?"
    "m" "Christ, what the hell is going on here?"
    "m" "I don’t blame any of you for what happened today, alright?"
    "m" "I should have controlled the environment more, that’s a failing of me as the club leader."
    "m" "I’m sorry, everyone."
    "m" "For the record, I just got off the phone with Ayaka; she wishes us well, but probably won’t be returning."
    "m" "So, I guess that’s that."  

    time day 16 hour 15 minute 33
    "s" "Sorry everyone, I'm a little late, but I've got the key!"
    "n" "All g, Yuri and I are just waiting outside"
    "y" "Take your time, we'll be here."
    "s" "Will do! I got caught up talking with Yona, because she wanted some advice!"
    "n" "Advice? What for?"
    "s" "Oh, ehe"
    "n" "Ah, that kind of advice"
    "n" "Yuri's giggling"
    "s" "Meanie!"
    "s" "It's not like I don't have experience!"
    "n" "No, that's exactly what it's like."
    "s" "Monikaaaaaaaa"
    "s" "They're bullying meeee"
    "y" "Bully? Never. We're just poking fun at the irony of the most perpetually single person being asked for relationship advice."
    "s" "Booooo"
    "s" "All of you are single too!"
    "y" "Yes, but that's by choice."
    "s" "Monikaaaaaaaaaaaa"
    "n" "Hot damn, someone's spitting fire over here"
    "s" "Natsuki help meeeee"
    "n" "Help you what, get a date?"
    "s" "Nooooooooo"
    "s" "Help me not be wrong!"
    "n" "Yeah, the only way to fix that is to get a date."
    "s" "Stop being meannnn"
    "n" "I'm just stating facts"
    "s" "Whyyyyyyyyyyyyyyyy"
    "m" "Well well, this took a turn."
    "s" "Monikaaaaaa"
    "m" "It's her choice to keep it that way, you two. Just like it's your choice to do the same."
    "y" "That might be true, but that doesn't mean it isn't a little entertaining."
    "m" "If you want them to stop, Sayori, you'll need to stop feeding them~"
    "s" "But Monikaaaaaaa"
    "m" "Up to you."
    "n" "Or you could just man up and date someone"
    "s" "Noooooooo"
    "s" "My pure innocenceeee"
    "n" "HA!"
    "s" "Monikaaaaaaa"
    "s" "She's still bullying meeeee"
    "m" "If it bothers you, ask her to stop."
    "s" "But but"
    "n" "But it's funny, right?"
    "s" "Maybeee"
    "n" "So you want us to continue?"
    "y" "Oh, my~"
    "n" "Okay, Yuri, you made it weird"
    "y" "Did I?"
    "s" "Yeah, a little"
    "m" "Alright, I'll get back to my meeting now. Enjoy your clubtime!"
    "s" "Nooooo"
    "s" "But yeah, almost there guys~!"
    "n" "Sweet"