init python:
    def get_m_a_gc_name():
        return "Aika" if pov_key == "m" else "Monika"

init phone register:
    define get_m_a_gc_name:
        add "m" add "a" 
        icon ConditionSwitch(
            "pov_key =='a'", phone.asset("monika_icon.png"),
            "True", phone.asset("aika_icon.png")
        ) 
        key "m_a" as m_a_gc
    
    time month 4 day 6 year 2016 hour 19 minute 34
    "a" "Hey, Monika, for the club tomorrow, could we potentially look at setting up some displays for the upcoming festival?"
    "a" "Sorry for texting you, by the way, rather than messaging, I just felt it was on the urgent side."
    "m" "Oh, the arts festival? That sounds like a fantastic idea. Perhaps we can put on a debate to show off the skills we’ve been practising, too."
    "m" "And don’t worry about it, I don’t mind if it’s text or messaging. Both work just fine."
    "a" "Alright, that’s a good idea. I’ll try and think up some ideas for it in the meantime. Would you be willing to look at setting up the displays themselves then?"
    "m" "Of course, I’ll put something together for you."
    "m" "Let me know how that goes for you and I’ll lend you some support where I can."
    "a" "Will do! See you tomorrow!"

    time day 6 month 5 hour 8 minute 31
    "a" "Hey Monika, I wanted to ask you something, when you have a moment."
    time minute 45
    "m" "Sure, go for it. Sorry, I was in the zone with my Maths."
    "a" "Ah, sorry to interrupt"
    "m" "No, I’d just finished when I noticed your text. What can I do for you?"
    time minute 55
    "a" "I’ve been thinking about a lot of things lately, and something that’s been on my mind is the thought that I probably wasn’t the best choice for your 2IC. We’re only in our second year; should we really be the ones leading this club when there are so many seniors? I’m not doubting your abilities or anything, not at all, I’m just surprised that you’d pick me over so many more capable and older candidates. Again, I don’t want to come across as undeserving or ungrateful, but it’s been bothering me for the past month that you went with me and not someone else."
    "m" "Aika, I picked you because I knew you would complement my own abilities as a leader, and that one day, it might fall to you to run a club like this yourself."
    "m" "I’m fully confident in your abilities and your skills. I picked you because there’s not just this year to worry about. Leaders aren’t just born; you need to be forged into one."
    "a" "That doesn’t answer why you’d pick me over someone more senior."
    "m" "Well, that’s simple. If I were to not keep this position next year, for whatever reason, and I’d picked a third-year, what would happen if I were to graduate?"
    "a" "There’d be no-one experienced enough to take your place?"
    "m" "Exactly. I’m not just setting things up for the short term; you always have to be looking at the bigger picture, right?"
    "a" "That does make sense, but then, why not a first-year?"
    "m" "Because I’m not thinking {i}that{/i} far ahead, aha~"
    "m" "Besides, that might actually ruffle some feathers, don’t you think?"
    "a" "True. Are you planning on leaving though?"
    "m" "Well, no, but you always have to be prepared for the worst."
    "m" "I’m going to keep on being prepared, as best as I possibly can, because sometimes life’s like that. It’s always full of surprises~"
    "a" "So you’re keeping me on my toes, is that it?"
    "m" "That’s the one~! And that’s what I expect you to do with the rest of the club, too. A complacent club is a club that isn’t worth funding."
    "a" "I see~ Given that you’re the daughter of the leaders of the P&C, it’d make sense that you know a thing or two about the financing of clubs."
    "m" "Cynthia was also the Student Council President last year, and she taught me pretty much everything."
    "a" "That’s true! Speaking of, why didn’t you run this year, like you did last year?"
    "m" "Oh, that’s simple. I’m already in charge of a club and I’m knee deep in cram school already."
    "a" "Ah, so you didn’t have the time to spare. Is that why you’re training me? So you can run for office next year?"
    "m" "Aha, no, actually. I have no plans of running next year either."
    "m" "Cynthia’s the type to lead from the front; I’m not really that kind of leader."
    "m" "I’m more of a manager than a speaker. Cynthia’s got that confidence."
    "a" "Isn’t that something you could build yourself, though?"
    "m" "Maybe, over time. Right now, I’ve got bigger things to focus on, I think."
    "a" "That’s fair. Let’s just get through this term first, shall we?"
    "m" "Exactly. One step at a time, for now. Once we’ve got the spare brain power, we can start looking into more and more of the goings on in our lives."
    "a" "You’re the boss~!"
    "m" "Aha, yep~"

    time day 15 hour 12 minute 15
    "a" "Ready when you are"
    "m" "I’ve been waiting for you, though?"
    "a" "... You went to the music room, didn’t you?"
    "m" "Yes?"
    "a" "That’s my bad, sorry. I’m actually in my classroom at the moment, I should have told you where I was"
    "m" "I see"
    "m" "On my way now"
    "a" "Cool!"

    time day 24 hour 15 minute 24 month 6
    "a" "Hey, where are you? We’re due to start"
    "m" "Sorry, I’m like thirty seconds away! I was called in to see the headmaster"
    "a" "Everything alright?"
    "m" "Yeah, absolutely, it was just about my academic scholarship"
    "a" "Let me guess, they said no?"
    "m" "Well, you know the school"
    "m" "They’ll find any reason to not give people free money"
    "a" "Let me guess, combined income?"
    "m" "Nail on the head"

    time hour 7 minute 31 month 7 day 2
    "m" "Hey, Aika, would you mind covering for me today? I have to head home early to sort some stuff out"
    "a" "Sure! What did you have planned?"
    "m" "I’ll email it all to you; it’s all there, all you have to do is hand out the docs"
    time minute 54
    "a" "Oh, wow, you weren’t kidding. These are great, thank you!"
    "m" "It’s the least I could do for skipping out on you!"

    time day 8 hour 9 minute 2
    "a" "Hey, thanks for dropping by with my homework yesterday. Sorry again for not giving you a heads up, just reaching for my phone was agony"
    "m" "No, don’t worry about it! I was just worried about you, is all"
    "a" "Aha, thanks. I don’t know what I’d do without you and Keiko"
    "m" "Things would be a lot less organised, I could promise you that aha"
    "a" "I don’t doubt it"
    "a" "Side note, I heard that Chiaki Sodatsu is running for President next term. I know it’s a little early to think about, but still."
    "m" "She’s an outsider to the region and the community, but she’s a born leader. If anyone’s going to take the presidency, it’ll be Chiaki."
    "a" "You’d get it, if you run"
    "m" "I might, but do you really want me to split my time between club and duties?"
    "a" "That’s true. Though"
    "a" "Do what makes you happy, alright?"
    "m" "Aha, I will. Right now I'm content just to have a strong support network. Best not to shake the tree"
    "a" "I suppose that’s true"
    "m" "So are you feeling better today?"
    "a" "Oh, a little. Gonna take another couple days off, I think, just to give myself time to recover"
    "a" "Would it be okay to ask you to drop off my work again?"
    "m" "I have cram school today, so if I do, it won’t be until pretty late. I could ask Yuri?"
    "a" "Sure. Does she know where she’s going"
    "m" "I’ll give her your address, don’t worry"
    "a" "Thanks, Monika"
    "a" "You’re literally an angel"
    "m" "Aha~ I get that a lot!"
    "a" "Wait really?"
    "m" "No, of course not. Imagine calling someone an angel."
    "a" "That’s what I was thinking. Kinda feels icky to think about"
    "m" "Yeah"
    "m" "Oh, gotta go, sorry"
    "a" "It’s all fine, don’t worry"
    "a" "See you when I get back"
    "m" "Will do!"

    time day 11 hour 18 minute 23
    "m" "Just letting you know that I won’t have my phone on me for about a month"
    "a" "Oh, did you break it?"
    "m" "No, got grounded"
    "a" "Ah, again?"
    "m" "Yep"
    "a" "That’s kinda a bummer"
    "a" "Makes planning a little harder"
    "m" "Sure does"
    "a" "That’s alright, we can just get to school a little early each day and plan the activities, if we need to"
    "m" "Sure, that sounds like a plan"
    "m" "Let’s organise to meet in the quad, at the south bench"
    "a" "Oh, right, yeah, because we won’t be able to communicate when we get there"
    "a" "Let’s try 8:15?"
    "m" "And if the other person isn’t there by 8:20, call it there?"
    "a" "Sure"
    "m" "Alright then"

    time day 27 hour 12 minute 14 month 8
    "a" "Hey, quick question for you. Have you seen where the leger went?"
    "m" "Last I checked it was in the cabinet"
    "a" "Yeah, I thought so too, but it isn’t there"
    "m" "Odd"
    "m" "Have you looked in the tech box"
    "a" "Have now"
    "m" "What about under the podium"
    "a" "Nope"
    "m" "Maybe ask in the staffroom"
    time minute 32
    "a" "Yeah, found it"
    "m" "Staffroom? Whatever for?"
    "a" "No, student council actually"
    "a" "Apparently their treasurer was doing an audit, and we should have been given plenty of notice"
    "m" "Oh, shoot! Was that today?!"
    "a" "Apparently?"
    "m" "That’s totally my fault"
    "m" "I didn’t realise we’re this far into the term already"
    "a" "Exams are like, a week and a half away"
    "m" "No, that I know about, it just"
    "m" "I dunno, didn’t click"
    "a" "You sure you’re feeling alright?"
    "m" "I think so"
    "m" "Just need to get some more sleep"
    "a" "Staying up all night studying isn’t going to help"
    "m" "It’s not that it doesn’t help, it’s that I need to find a balance"
    "m" "But I don’t have time for that, not with my position at the top on the line"
    "a" "Oh, you mean the two girls who have been encroaching on your number one spot?"
    "a" "You can’t always expect to be better than everyone else"
    "m" "No, but I can expect to be more driven"
    "a" "You think?"
    "a" "If you’re concerned, maybe reach out to the two of them and form a triumvirate."
    "m" "So I can sabotage them?"
    "a" "No! So you can work together and raise each-other up to even greater heights!"
    "m" "I know, I know. I’d never do that"
    "m" "Unless I had to"
    "a" "Geez, you’re absolutely ruthless when you’re tired"
    "m" "Maybe"
    "m" "But you have to step on a few heads to crawl to the top"
    "a" "See, this is why I don’t compete with my grades. I’m in the top ten percent, and that’s good enough for me"
    "m" "Yeah, at least you have that option"
    "a" "Fair"
    "m" "Sorry, I’ve got to go. I’ll keep that in mind, though"
    "a" "Sure, it might actually pan out better than you expected"
    "m" "Let’s hope!"

    time day 4 month 9 hour 17 minute 16
    "a" "Hey Monika, is everything alright? You seemed a little out of sorts today"
    "m" "Yeah, I’m alright, it’s just been a bit of a stressful week"
    "a" "Anything I can help with?"
    "m" "I mean, I wouldn’t complain, but I doubt it"
    "a" "Try me"
    time minute 26
    "m" "I guess, it’s just everything’s getting to me in a way that it hasn’t before. I’m drained more than I usually am, my fuse is shorter and I find myself dragging my heels more often. It’s like I’m a beetle lying on its back. Last week I snapped at Yuri; I’ve never done that before, and I don’t know what came over me. She’s been my strongest supporter for as long as I’ve known her, and she doesn’t deserve this kind of treatment. I’m just"
    "m" "I feel like a mess, like I’m not able to do any of the things I want to, much less the things I have to."
    "a" "It sounds like you need some time off, Monika"
    "m" "Time off from what? Life?"
    "a" "From everything. Take some time to relax and destress"
    "a" "Get some sleep"
    "a" "Take a sick day or two"
    "m" "Oh, like that’d work. There’s no way I’d be allowed to"
    "a" "All you can do is ask, Mon"
    "m" "Fine"
    time hour 18 minute 21
    "m" "I don’t know what you did, but they agreed to give me the rest of the week off"
    "a" "What’d I tell you?"
    "m" "Guess I owe you one"
    "a" "Aha, don’t make promises you can’t keep~"
    "m" "I know, I know. Thanks, Aika"
    "a" "You’re very welcome. I’ll keep an eye on things until you’re back"
    "m" "Yeah, I’ll be counting on you"

    time day 27 hour 17 minute 19
    "a" "Hey, did you mention the ledger inconsistencies we noticed the other day to the student council?"
    "m" "I did, why?"
    "a" "Ah, no worries, one of the prefects dropped by while I was in class asking about it"
    "m" "Ah, really? I thought they’d come see me first"
    "a" "Who knows? Maybe because the ledger is one of my duties?"
    "m" "Possibly, though how they would have known that is beyond me"
    "a" "Agreed. Either way, I’ve organised a meeting for us and the SCP on Wednesday to get it sorted out"
    "m" "Fantastic, that’ll make our lives easier"
    "a" "Tell me about it. Having to triple-check every expense and record it in two different ledgers is a huuuge pain in the ass"
    "m" "I could imagine. Thanks, Aika"
    "a" "Hey, just doing my job! That’s why I’m here, after all"
    "m" "I couldn’t do it without you~"
    "a" "Music to my ears~"

    time month 10 day 16 hour 19 minute 32
    "m" "Quick heads up that I’m not going to be there tomorrow; I only just remembered that I’m heading into Tokyo to catch up with my sister."
    "a" "Oh, that’s no problem! Have fun!"
    "m" "I will~! I haven’t seen her in months, and I’m looking forward to it."
    "a" "Special occasion?"
    "m" "I wouldn’t say so, more that she’s simply got a free day and asked if I’d be willing to spend it with her."
    "a" "That’s awfully nice of her to want to spend her day off with you. It must be nice having a sister."
    "m" "It is; someone to make the mistakes first so that you can learn from them, someone to give you a guiding hand, someone to look up to."
    "a" "I see, that does sound handy from a pragmatic view."
    "m" "But also from the view of the fact that she’s someone who cares about me. Sometimes that’s a little hard to come by, these days"
    "a" "Yeah, I totally get you. Anyway, enjoy your day!"
    "m" "I shall!"

    time day 27 hour 12 minute 2
    "a" "Just a heads up that I’ve got a meeting with the Headmaster this afternoon, so I’m not gonna be there."
    "m" "Everything alright?"
    "a" "Yeah, just discussing my bid for a seat on the Student Council."
    "m" "Oh? You’re going through with it after all?"
    "a" "I mean, there’s no harm in running; Chiaki’s probably going to win, to be fair, but I wouldn’t mind a prefect role."
    "m" "I can see the logic; sure does look good on a resume."
    "a" "You sure you don’t want to run with me?"
    "m" "I mean"
    "m" "Maybe, but considering how busy I am with the club already, it’s probably a bridge too far."
    "a" "I getcha. If you’re that stressed though"
    "m" "Hey, don’t talk like that. Contrary to what you might think, I actually enjoy the Debate Club."
    "a" "You sure? It sometimes feels like that’s not the case."
    "m" "Just because I’m forced to be there, doesn’t mean that I can’t enjoy it. Just like school."
    "a" "That’s a good point, but that still doesn’t change the fact that sometimes I’m a little worried about you."
    "m" "I appreciate it."
    "m" "I really do, you’re a huge rock for me, Aika"
    "a" "Aha, I do my best~"
    "a" "Either way, the club’s still gonna be my first priority. You can rely on me~"
    "m" "I look forward to working with you more~!"
    "a" "That’s the spirit! Lean on me, and I’ll lean on you - That way everyone wins!"
    "m" "Yep~"

    time day 4 month 11 hour 7 minute 21
    "m" "Hey Aika, just a heads up that I’ll have to leave a little early today. I’ve got some things to take care of at home."
    "a" "No sweat! We’re pretty much ready for the festival as is, so that won’t be a problem. I’ll get a couple of the newbies to help me with some research for that last debate; it’ll be good practice for them."
    "m" "That’s a good idea; get them into the swing of the work that goes in before the debate, as well as during"
    "a" "That’s the plan~!"

    time day 7 hour 8 minute 42
    "a" "Hey, I’m running a touch late today, got held up at home"
    "m" "It’s totally fine! I’m already here, everything’s been set up"
    "a" "I literally have no idea what I’d do without you"
    "m" "Aha, good thing we won’t have to find out~!"

    time day 11 hour 18 minute 44
    "a" "Would you mind running over these notes real quick when you have a second for our next debate?"
    "m" "Sure! I’m guessing you’ve emailed them?"
    "a" "Sure have~"
    "m" "I’ll have a look and let you know if there’s anything out of place"
    time hour 20 minute 3
    "m" "I had a look, and I did have a question"
    "a" "Sure"
    "m" "You mention the rate of deaths to births here, but you don’t have a source for the data points or graph you use"
    "a" "Oh, didn’t I? I’ll adjust it"
    "m" "Sure. It’s one of those things that you might not notice if you’re just watching the debate, but if your audience is actively engaged in it, it’ll stick out like a sore thumb that you’ve not included a reference."
    "a" "Yeah, I can see why; the slide does feel a little barren, actually, and that’s probably why"
    "m" "That’d be my guess; you knew something was missing in the back of your mind, but couldn’t pin it"
    "a" "Thanks for picking up on it; I’d probably have missed it otherwise"
    "m" "It’s the least I can do~"

    time day 26 hour 8 minute 13
    "a" "Would you mind if I skipped out on the club today? I’ve been asked to see a teacher after class about my History, and it might take a while."
    "m" "That’s alright, we’re getting close to exams, so it’s probably smart to take some time to prepare."
    "m" "We’re not meeting exam week anyway, so it shouldn’t be a big problem"
    "a" "You’re the best"
    "m" "I know~"   

    time day 24 month 12 hour 12 minute 3
    "a" "Merry christmas!"
    "m" "To you, too! Are you well? Not out in the cold, I hope~"
    "a" "Oh, no, I’ve been out here all morning. The kids across the street have been building castles and men, then using them as shields from the torrents of snowballs"
    "a" "I’m in the lead~"
    "m" "You’ve been bullying the neighbours’ kids?"
    "a" "I prefer the term 'tough love'~"
    "a" "They have to learn that life’s unfair somehow, after all"  
    time minute 21
    "a" "I don’t wanna play this game anymore"
    "m" "What happened?"
    "a" "They all ganged up on me"
    "m" "Oh no, who could have seen this coming?"
    "a" "I’m not kidding! Try having ten kids charging at you, armed to the teeth with snowballs, and see how you like it!"
    "m" "See, the difference is, I don’t make fun of them for being kids"
    "a" "It’s not my fault they’re like ten years younger than me!"
    "a" "Just because they’re small doesn’t mean you can’t teach them the hard lessons"
    "m" "Looks like it was they who taught you, though"
    "m" "The bigger they are, the harder they fall?"
    "a" "Oh, bite me"
    "m" "All I’m saying is you shouldn’t get too carried away"
    "a" "What, like you?"
    "m" "Touché"

    time day 7 month 1 year 2017 hour 13 minute 24
    "a" "As school goes back on Monday, I thought now would be a reasonable time to discuss our plans for the term"
    "m" "It heavily depends on how the first few weeks go. I’d prefer to play it by ear"
    "a" "Are you still angry?"
    "m" "It isn’t that I’m angry, Aika. You can do as you please"
    "m" "Please don’t mistake my apathy for anger, I’m more concerned with the outcome than the path getting there."
    "m" "If this is what you want to do, go do it. Don’t feel obligated to the club, or to me"
    "a" "If you’re sure"
    "m" "I’m absolutely certain. Stay, if you want to, go, if you want to"
    "m" "I don’t want you to feel restricted, just as I know you’d do the same for me"  

    time day 9 hour 5 minute 31
    "a" "You’re going to be upset with me, but I made my decision."
    time hour 6 minute 3
    "m" "If you’ve dropped out of the running, I won’t be upset, as long as you decided it for yourself."
    "a" "This club needs me, and there’s too much left for me to do here."
    "m" "It doesn’t need you, Aika. It survived before you, and it will after you. Do what YOU want, not what you think someone expects of you."
    "a" "Like you do?"

    time day 18 hour 15 minute 11
    "a" "Any chance you can grab the keys from the staffroom on the way out?"
    "m" "I can, why?"
    "a" "Looks like the lock has been changed"
    "m" "That’s annoying"
    "a" "Tell me about it"

    time day 30 hour 14 minute 21
    "m" "Aika, I don’t understand"
    "a" "You don’t have to understand, it had nothing to do with you"
    "m" "It feels like it does"
    "a" "Well, it doesn’t."
    "a" "I dropped out because I wanted to, not because of anything else"
    "a" "If you’re going to be upset, save it. Let’s just do our jobs, okay?"
    "m" "Okay"
    "m" "If that’s what you want, I won’t bring it up again"
    "a" "Good"

    time day 19 month 2 hour 7 minute 44
    "a" "You were serious about what you said yesterday, weren’t you?"
    "m" "I’ve been strongly considering it"
    "a" "If you do this, it’ll create a huge rift, you know that right?"
    "m" "Between myself and the club? Of course I know that"
    "m" "Elections are coming up, technically. It’d be simple enough"
    "a" "That’s not how elections work around here"
    "a" "The Debate Club does things differently, and you know that"
    "m" "I do"
    "a" "So why?"
    "m" "Because I’m tired, Aika"
    "m" "Of all of this, of everything"
    "m" "You said yourself that you’d probably step down anyway. What’s the harm?"
    "a" "It’s not the harm, it’s just"
    "a" "We’re almost at the end of term, end of the year"
    "a" "Worse, it feels like"
    "a" "Like running away"
    "m" "Like what you tried to do?"
    "a" "I wasn’t running, I was side-stepping, but I didn’t even do that"
    "m" "So now you’d stand in the way of me doing the same?"
    "m" "I’m not running"
    "a" "That’s what it feels like"
    "m" "You don’t have to stay"
    "a" "What would happen if I don’t?"
    "m" "They’d have to restructure? What’s wrong with that?"
    "a" "I"
    "a" "Look"
    "a" "If you leave, it"
    "a" "We all get screwed"
    "m" "I don’t want to be constricted, Aika. I thought you of all people would understand me on this, considering your stance only a few weeks ago"
    "a" "I do, I understand, and I won’t stop you"
    "m" "It sure feels like you’re trying to stop me"
    "a" "Just go, if you want to go."
    "m" "I haven’t decided anything yet"
    "a" "Well"
    "a" "Not deciding puts me in limbo"
    "a" "I don’t like that"
    "m" "So you’re saying whatever I decide, decide soon"
    "a" "Something like that"
    "m" "I’ll take it under advisement."
    "a" "Either way, I’m keeping my mouth shut. You’ll get in trouble if this gets out"
    "m" "Yeah, no kidding"

    time day 20 hour 17 minute 11
    "a" "Monika, for what it’s worth…"
    "m" "Please, just stop"
    "a" "You didn’t let me type out my thoughts."
    "m" "No, I didn’t."
    "a" "There’s nothing I can do to change your mind?"
    "m" "No"
    "a" "hen… Good luck."
    "m" "Thank you, Aika."
    "m" "I’m…"
    "m" "I’m sorry."
    "a" "I know you are."
