init python:
    def get_m_cy_gc_name():
        return "Cynthia" if pov_key == "m" else _("Mon")

init phone register:
    define get_m_cy_gc_name:
        add "m" add "cy" 
        icon ConditionSwitch(
            "pov_key =='cy'", phone.asset("monika_icon.png"),
            "True", phone.asset("cynthia_icon.png")
        ) 
        key "m_cy" as m_cy_gc
    
    time day 6 month 4 year 2016 hour 18 minute 21
    "cy" "Are you home yet, Monika?"
    "m" "I’ve just arrived, why?"
    "cy" "Oh, good. There should be a package arriving in about ten minutes. Would you mind signing for it and placing it just inside my door?"
    "m" "I don’t see why not. I’ll let you know when it arrives."
    "cy" "Thank you. It was supposed to be shipped to my dorm, but I must have forgotten to adjust my address."
    "cy" "It isn’t anything urgent, it can wait until the end of term, it’s just a shame."
    "m" "Sure."
    time minute 34
    "m" "I’ve put it inside your room, as you asked."
    "m" "You sure you don’t want it shipped out to you?"
    "cy" "I’m sure. Thank you, I don’t know what I would have done without you."
    "cy" "I’ll bring you some of that coffee you really liked with me when term finishes."
    "m" "Really? That would be fantastic!"
    "cy" "My pleasure. I’ll see you in a couple months, sis."
    "m" "It has been oddly quiet around here without you, if I’m being honest."
    "cy" "That doesn’t surprise me. I imagine our parents have been slogged with work, and you’re hardly home either between school, cram school, running the debate club and the student council."
    "m" "Oh, right, about that."
    "m" "Yeah, I didn’t run this year."
    "cy" "Wait, really? But if you snagged prefect this year you’d be poised to get Student Council President for your last year?"
    "m" "Yes, I would, but"
    "m" "I’ve decided I don’t want to run for it."
    "cy" "Have you spoken with our parents about it?"
    "m" "Are you kidding? They’d kill me."
    "cy" "That’s why I was surprised you haven’t been grounded already."
    "cy" "They’re the head of the P&C. There’s no way they don’t already know."
    "m" "That’s what scares me."
    "cy" "Mon, I’m not around to protect you anymore. I need you to be more careful."
    "cy" "If something were to happen to you..."
    "cy" "I don’t know what I’d do."
    "m" "I’ll be alright. I’ve made some calculated decisions."
    "m" "... I just have to hope I’m not horrid at maths."
    "cy" "Please keep me in the loop. I may not be able to do much, but I’ll do what I can."
    "m" "Thanks, sis. I appreciate it."
    "cy" "Hey, you’re spreading your wings, testing your independence. I’m one hundred percent behind you; you’ve gotta grow up sometime."
    "m" "Yeah, that’s what I’ve been thinking."
    "m" "Thanks for your support, sis. I really appreciate it."
    "cy" "You’re my baby sister, of course I’m going to do what I can. Stay safe, alright? Don’t go poking the ant nest."
    "m" "I won’t."  

    time day 19 hour 15 minute 14
    "cy" "Mon, have you been keeping an eye on the visitors lately?"
    time hour 16 minute 3
    "m" "No? Why on earth would I do that?"
    time minute 11
    "cy" "No reason, don’t worry about it. It’s just something I haven’t been able to do while I’m so far away, so I haven’t really been able to pour too much time into it"
    "m" "Why would you be interested in the visitors?"
    "cy" "Not 'interested', per say, more just curious as to what goes on sometimes."
    "m" "It feels like something we should definitely not be poking our noses into"
    "cy" "You aren’t the least bit curious?"
    "m" "No, not really. Not when I’m not the favourite."
    "cy" "I suppose you’d only want to stick your neck out so far..."
    "cy" "That’s alright, I’ll find another way."
    "m" "What are you so curious about?"
    "cy" "Nothing really specifically, more that we have a group of regular visitors that come by a couple times a year, and it just feels a little odd."
    "m" "Are they not allowed to have friends?"
    "cy" "Well, these are like, I dunno, young people"
    "cy" "Our age, kind of thing."
    "m" "You sure they’re not just clients?"
    "cy" "Sure don’t feel like it"
    "cy" "Though they could just be some kind of apprentice or intern who occasionally stop by the house for whatever reason"
    "m" "That seems just as likely, but also not, knowing them"
    "cy" "Right? But no good talking about it"
    "m" "True enough. I’ll see if I can keep an ear out"
    "cy" "I really appreciate it, Mon"
    "m" "You find hobbies in the strangest things, I swear..."
    "cy" "That’s me~"

    time day 17 month 10 hour 8 minute 21
    "m" "I’ll be arriving on campus in about fifteen minutes."
    "cy" "Perfect timing! I’ve just finished one of my assignments."
    "m" "This early in the morning?"
    "cy" "Of course! I only had some polish left when I put it down last night, but it’s important to get a full night’s sleep."
    "m" "Fair, I suppose. Why the rush though?"
    "cy" "It’s due next week; I have to make sure I polish it, then give it a couple of days away while I focus on other work before I give it a final check and submit it."
    "m" "Allowing for your days away from it, I see?"
    "cy" "Always"
    "cy" "How else could we possibly be expected to do half the things put on our plate if we aren’t organised?"
    "m" "Blind luck?"
    "cy" "Essentially~"
    "m" "Hence why the only sure way is to be organised."
    "cy" "If you complete your work before it’s due, you don’t have to worry about when things go wrong."
    "m" "True enough"
    "cy" "I’m just outside the cafeteria, by the way. There are signs to point you there from the front."
    "m" "Sweet, see you in a moment!"   

    time day 4 month 12 hour 15 minute 24
    "cy" "Did you want me to pick you up?"
    "m" "Oh, I’m already on my way, the butler swung by."
    "cy" "Ah, well. I hope you’re prepared for a fun night"
    "m" "Yes, fun. Let’s go with that."
    "cy" "No point being sour; it’s going to happen whether we want it to or not. We should just be happy that it’s not at our expense this time."
    "m" "Agreed"
    "cy" "Stop by my room when you get home and I’ll help you do your hair. We can have a talk about it then"
    "m" "Alright, I’ll see you then"

    time day 23 month 2 year 2017 hour 20 minute 11
    "cy" "Yuri told me."
    "m" "She promised!"
    "cy" "I don’t think she did it maliciously."
    "cy" "She’s worried about you."
    "m" "She has enough to worry about before she gets caught up in my problems."
    "cy" "That’s what friends do, Mon."
    "cy" "She’s trying to help you."
    "m" "I don’t want her help with this. I don’t want anyone getting dragged into my mutiny."
    "cy" "The fact that you’re brave enough to go through with any of this is the true miracle here. Yuri wants to support you in this."
    "cy" "Why don’t you let her?"
    "m" "I don’t want anyone else sticking their neck out, you of all people should understand that"
    "cy" "I do Mon, but the way you’re going about this..."
    "m" "Am I not old enough to make my own decisions?"
    "cy" "I don’t think you want me to answer that."
    "m" "Well, it’s too late anyway. I’ve already resigned."
    "cy" "Mon, your friends are worried about you - That’s all. They aren’t judging you for your decision, and they aren’t attacking you."
    "cy" "If that’s how you see it, then they’ve already lost."

    time day 25 month 3 hour 13 minute 13
    "m" "When are you home?"
    time hour 14 minute 2
    "cy" "I’m in the taxi now, should be about ten minutes."
    "m" "Ah, good timing. I might need you to help with something."
    "cy" "Keeping secrets again?"
    "m" "That question’s a trap."
    "cy" "It could be~"
    "m" "Cynthia, I’m really not in the mood for games today."
    "cy" "You alright?"
    "m" "No, not particularly."
    "m" "Let’s just say that things aren’t going too well over here."
    "cy" "Father?"
    "m" "Father."

    time day 3 month 5 hour 8 minute 1
    "cy" "Good luck, Mon. Don’t fret over last term, I’m sure you’ll manage this time."
    "m" "Thanks, sis. I really hope so."
    "cy" "As for your idea... Don’t tell our parents, but I tacitly approve."
    "m" "Really?"
    "cy" "You’ve earned a break from debating, and you’ve earned a break from leading."
    "cy" "If you want my advice..."
    "cy" "Join the robotics club for your final year."
    "m" "Really? Robotics?"
    "cy" "Yes, I think you’d do well, but more importantly it will give you a chance to not be in charge for once."
    "m" "I’m not sure."
    "cy" "It’s the only other truly well-established club in the school. If you pick something else, you may end up running it if you aren’t careful."
    "cy" "Surely you don’t want another repeat of your first year?"
    "m" "I guess not."
    "m" "But I was thinking"
    "m" "What if I started my own club?"
    "cy" "What?"
    "cy" "Why on earth would you do that to yourself?"
    "m" "Well, like-"
    "m" "It would be smaller, something to really call my own."
    "cy" "Mon, you don’t need to start a club to form an official study group."
    "m" "Nono, it’s not just a study group. I want a place where people can come together."
    "cy" "That sure sounds like a study group."
    "m" "It’s hard to explain."
    "cy" "Well..."
    "cy" "Starting a club would take a month or more. You probably wouldn’t have it finished until toward the end of term."
    "m" "I’ve already found a teacher willing to sign off on it."
    "cy" "Oh? So you know what the club will be about?"
    "m" "Well..."
    "cy" "Mon, seriously."
    "m" "I mean I have an idea!"
    "m" "It’s just..."
    "m" "You’ll make fun of me."
    "cy" "Of course I will; you’re my sister."
    "m" "I’m thinking of starting a literature club."  
    time minute 41
    "cy" "Please say sike."
    "m" "I’m serious!"
    "cy" "You’re mad."
    "cy" "Every time - and I mean every time - A literature club has been started at this school, it’s folded within a year."
    "m" "I know! I know, but doesn’t that kinda make it all the more exciting? What if this is the one?"
    "cy" "Or you just go down in history as another failed club?"
    "m" "Maybe, but"
    "m" "That might have to just be a chance I need to take."
    "cy" "Alright, let’s say y0u start one."
    "cy" "Who’s joining?"
    "m" "... I haven’t gotten anyone yet."
    "cy" "Mon, I know this is your big strike out, but if you do this unprepared it will bite you."
    "cy" "You know what our parents are like."
    "cy" "You have one shot, one opportunity."
    "m" "And I will capture it. I have to."
    "cy" "Then I hope you know what you’re doing."
    "m" "... So do I."
    "cy" "Love you, baby sis. I’ll see you toward the end of the year."
    "m" "Thank you. Honestly."
    "m" "Love you too, big sis."

    time day 17 month 8 hour 18 minute 19
    "cy" "So tell me how it's going."
    "m" "Better than I could have asked for, honestly."
    "m" "Yuri’s pushing back a bit, but I expected that. It's..."
    "cy" "She's jealous?"
    "m" "She is."
    "m" "I don't know what to do. I can't very well be expected to not have friends, can I?"
    "cy" "Mon, I like Yuri, I do, but you have to ask how much is too possessive."
    "cy" "She doesn't own you, and she can't expect you to just be hers one day."
    "m" "I get that but"
    "cy" "You don't owe her anything, sis. She's your friend."
    "cy" "Not your mother."
    "m" "Sometimes I wonder if it's something I did. Am I just projecting something others gravitate to?"
    "cy" "Sis, you're pretty, sporty, intelligent and wealthy. There's not a boy in that school who isn't into you; it shouldn't be a surprise that some of the girls are too."
    "m" "But I've known her for so long, and it's still..."
    "m" "It feels more like she’s dependent rather than anything else."
    "m" "I've always known she's a little selfish, but I don't know how to feel about this now."
    "m" "If she's going to try and stop me from making friends, it feels like"
    "cy" "Don’t do anything rash just yet. Maybe talk with her about it."
    "m" "Are you kidding? She's die of embarrassment if she found out I knew!"
    "cy" "Yes, but would that not be better than trying to tiptoe about it for the rest of your lives?"
    "m" "Cynthia..."
    "cy" "Better that than either alternative."
    "cy" "She can't be mad at you for picking up on signals."
    "m" "You don't know her like I do"

