init python:
    def get_m_y_gc_name():
        return "Yuri" if pov_key == "m" else _("Yu")

init phone register:
    define get_m_y_gc_name:
        add "m" add "y" 
        icon ConditionSwitch(
            "pov_key =='y'", phone.asset("monika_icon.png"),
            "True", phone.asset("yuri_icon.png")
        ) 
        key "m_y" as m_y_gc
    
    time day 4 month 3 year 2016 hour 9 minute 54
    "m" "I got my new phone today, Yuri! I’ll have to show you, it’s amazing!"
    time minute 2 hour 10
    "y" "Next time we’re at school, then?"
    "m" "I’ll see you in class! I’m heading home now, so I won’t be able to talk as much."
    "y" "Worry not, I shall see you when next I see you."
    "m" "Bye!"
    "y" "Farewell, my friend."

    time day 11 month 4 hour 16 minute 1
    "m" "Hey Yuri, have you left school yet?"
    "y" "No, why?"
    "m" "We wrapped up the club a little early today so that we can prepare for the arts festival next week. I was wondering if you wanted to walk home with me?"
    "y" "You’re not getting a lift?"
    "m" "I really feel like walking today, so I haven’t even mentioned it yet."
    "y" "Alright, I’ll meet you at the school gate in a few minutes. I’m just in the library."
    "m" "I can meet you there, if you want? We don’t have to head off right away or anything."
    "y" "In that case, please do. I’m just doing some research; I’m almost finished."
    "m" "See you in a moment, then!"

    time day 24 hour 8 minute 24
    "y" "Would you perhaps have some time this afternoon? I would like to go for a walk."
    "m" "Would you like me to come with you?"
    "y" "I"
    "y" "Erm, yes, that was what I was getting at."
    "m" "Sure, I can free up some time. Regular place?"
    "y" "Yes, would half-past-four work for you?"
    "m" "If it doesn’t, I’ll let you know, but it should be fine."
    "y" "Wonderful! I look forward to it."
    "m" "See you there!"    

    time day 7 month 5 hour 12 minute 23
    "y" "Apologies, but I seem to be running a little behind schedule. My teacher requested I stay behind after class to discuss my report."
    "m" "Oh, that’s alright! I’m just in the music room; Aika’s playing some lovely music on the piano here."
    "y" "Is that so? I shall do my best to arrive as soon as I can."
    "m" "No need to rush, Yuri, take your time and breathe."
    "y" "Yes, thank you."
    "y" "I will be there in a few minutes."
    "m" "Looking forward to it~!"

    time day 15 hour 11 minute 11
    "y" "Do you have plans for lunch today?"
    "m" "Sorry, I’m studying with Aika, but if you’d like you can join us?"
    "y" "Oh"
    "y" "That’s quite alright, I’ll spend some time in the library."
    "m" "Sure! Be safe, alright?"
    "y" "I will"    

    time day 25 month 6 hour 6 minute 2
    "y" "When you’re awake, would you mind letting me know?"
    time minute 8
    "m" "Sure, what can I do for you?"
    "y" "I was hoping you might be able to take some notes for me today, as I’ve woken up quite ill."
    "m" "Of course! I’ll bring them over after school and we can have a study session, if you’re feeling a little better by then."
    "y" "Don’t you have cram school today?"
    "m" "I do, but I don’t have to stay the entire time if I get all my work done quickly"
    "y" "If you insist. I’ll let you know how I’m feeling about 4pm."
    "m" "Sure!"
    time hour 16 minute 12
    "m" "Hey, how are you feeling?"
    time minute 31
    "m" "Yuri?"
    "m" "I’m guessing you’ve fallen asleep, right?"
    time hour 23 minute 51
    "y" "I’m terribly sorry, Monika, I had fallen asleep. I hope you didn’t come by to check on me..."

    time day 26 hour 6 minute 1
    "m" "Oh, no, I wasn’t going to show up if you didn’t respond, don’t worry. I hope you’re feeling better today though!"
    time hour 10 minute 14
    "y" "No, not overly. I might just rest once again, I’m sorry"
    "m" "Don’t sweat it, just relax. I’ve been keeping notes for you."
    "y" "Thank you so much, Monika"
    "m" "Hey, what are friends for, right?"

    time day 30 minute 40 hour 14
    "y" "I’ll be at the fountain after school."
    "m" "Sure, I’ll see you then!"

    time day 11 month 7 hour 17 minute 51
    "m" "Hey, just letting you know that I’ve been grounded for a month. Not gonna have my phone on me or be able to hang out"
    "y" "What happened?"
    "m" "I ran my mouth"
    "y" "Into what, a blender?"
    "m" "Hm"
    "y" "It seems my attempt at levity has fallen short"
    "m" "Sorry, just not in a great mood"
    "m" "I’ll see you at school, probably, so we’ll still be able to hang there"
    "m" "Just wanted to give you warning"
    "y" "Very well"
    "y" "Stay safe"
    "m" "I’ll do my best. You too"
    "y" "To the best of my ability" 

    time day 21 month 8 hour 4 minute 2
    "m" "Hey, Yuri, heads up that I got my phone back"
    "y" "Finally"
    "m" "So much for a month"
    "y" "What took it so long?"
    "m" "They forgot"
    "y" "You’re kidding"
    "m" "Nope"
    "m" "They straight forgot that they had it"
    "y" "Did you remind them?"
    "m" "Well, yeah"
    "m" "But by the time they got around to thinking about it, it’d already conveniently slipped their minds."
    "y" "Love that"
    "m" "So how are you today?"
    "y" "I’ve been practising yoga"
    "y" "It’s quite relaxing"
    "m" "Yoga? That’s different"
    "y" "Indeed, but I found this old cassette tape which walks you through several routines"
    "y" "It belonged to my mother"
    "m" "Ahh"
    "m" "It’s nice that you’re able to look back now at these things"
    "y" "It certainly wasn’t easy"
    "y" "It took almost everything I had to open those boxes, but it had to be done sooner, rather than later"
    "m" "I’m proud of you, Yuri"
    "y" "Thank you"
    "y" "That means a great deal to me"
    "m" "I’m always proud of you, you’re my best friend"
    "y" "And you, mine"
    "m" "Thank you for sticking with it. I know how much that must tear you up."
    "y" "It’s what I do best, is reflection."
    "y" "In any case, I unfortunately have some things to attend to. I’ll see you at school?"
    "m" "Of course you will"
    "m" "I’m smiling for you, Yuri"
    "m" "Even when you can’t find the power to smile for yourself"
    "y" "{i}{u}Message deleted.{/u}{/i}"
    "y" "Yes, and I appreciate you more than I could ever show"
    "m" "Enjoy your day, Yuri"
    "y" "And you, yours."   

    time day 30 hour 11 minute 12
    "y" "I just wanted to apologise for my outburst yesterday. It was completely out of line."
    time minute 34
    "m" "No, not at all! Seriously, that was my fault; I don’t know how I could have possibly missed something like that"
    "y" "Even so, snapping at you wasn’t the answer"
    "m" "Perhaps not, but even so, I still apologise."
    "y" "For the record, now that you know, well"
    "y" "I hope that it doesn’t make you think less of me."
    "m" "How could I think less of you? You’re my best friend, Yuri"
    "y" "I just thought that perhaps"
    "y" "Perhaps you might not want to be"
    "m" "Yuri, you know that there’s not a thing you could do or say that would turn me against you. Even if you came to resent me, I could never do the same."
    "y" "I see"
    "y" "Then I apologise for mischaracterising you"
    "m" "Apology accepted"
    "y" "For..."
    "y" "For the record, just so that we’re clear, the pen..."
    "m" "You can keep it, that’s alright"
    "y" "No, I mean"
    "y" "I understand. I might not want it back"
    "y" "But I"
    "y" "I wanted to say that there might have been a miscommunication"
    "y" "All I did was keep it with me"
    "m" "Wait, so you didn’t"
    "y" "No! I could never"
    "y" "That was what I was afraid of, that you’d think that!"
    "m" "Oh, thank god"
    "m" "That’s a whole lot less awkward now"
    "y" "Thank goodness"
    "y" "That was the impression that I thought you took away, when I thought about it a little"
    "y" "You could imagine how horrified I was when it occurred to me"
    "m" "Oh, yeah. When you said 'I took your pen to bed', well"
    "y" "Perhaps I should take more care in my choice of words in the future"
    "m" "Yeahhhh"
    "m" "So we’re alright?"
    "y" "If you’re alright, then we’re alright"
    "m" "Yeah. We’re good"
    "y" "I apologise for giving you the wrong impression and for worrying you."
    "m" "Don’t worry about it, I promise I’m not upset"
    "y" "If you’re certain"
    "m" "I am. To prove it, I’m taking you out tomorrow"
    "y" "Y- You are?"
    "m" "Yep. Smoothies?"
    "y" "That would be"
    "y" "Yes, I’ll be there."
    "m" "Alright, regular place and time?"
    "y" "I look forward to it." 

    time day 31 hour 21 minute 31
    "y" "Thank you for today"
    "y" "I can’t remember the last time we were together like this, able to just spend time amongst ourselves."
    "m" "It hasn’t been since we got into senior school, at least"
    "y" "Perhaps it is something we should revisit more often?"
    "m" "I’d love to. With our workloads ever growing, I think it’d be smart to set time specifically aside to unwind"
    "y" "Then is there somewhere you might like to go, next time?"
    "m" "Actually, there’s a pet store in the mall where they get a lot of rescue animals in and help rehabilitate and rehome them"
    "m" "I sometimes drop by to see how all the little ones are doing"
    "y" "Oh? I’m surprised that I’ve not heard of it."
    "m" "It keeps a reasonably low profile; the doctor who runs it is doing it as a passion project, rather than anything serious"
    "y" "I see. Shall we drop by on our way home from school sometime?"
    "m" "I’d love to"
    "y" "Then that is what we shall do."
    "m" "I shall wait with baited breath~"
    "y" "As will I, of course."
    "y" "The mistress of the night calls to me; I must take my leave."
    "m" "Then may the mistress gently beckon you to the steps of Eve."
    "y" "Farewell, maiden of the world, may your rest be bliss."
    "m" "Such a blessing I would, pray, wish for you, as all else would be remiss." 

    time day 4 month 9 hour 18 minute 24
    "m" "Hey, just letting you know I’m taking a couple days off. I was gonna call you like usual, but I might just get an early night. Talk to you in the morning?"
    "y" "I’ll give you a call as I walk to school, if that would suit you?"
    "m" "Sure, talk to you then"
    
    time day 17 hour 21 minute 11
    "y" "By any chance, might you still be awake?"
    "m" "I was just winding down after some study; what can I do for you?"
    "y" "Might you have a few moments for a call?"
    "m" "Of course"
    
    time day 18 hour 11 minute 2
    "y" "Thank you for yesterday, I was a little overwhelmed."
    "m" "Hey, that’s what friends are for, right?"
    "m" "I don’t mind you leaning on me"
    "y" "Yes, though I would rather not burden you with such matters."
    "m" "It’s no burden, Yuri. You’re my friend, and seeing you smile warms my heart."
    "y" "You’re utterly too kind."
    "m" "Aha, maybe I am, but only because you deserve it."
    "y" "Nonetheless, know that I do very much appreciate you, Monika."
    "m" "I know, and I appreciate you, too."
    "m" "I hope you enjoy your day!"
    "y" "And you, yours."   

    time day 22 hour 0 minute 0
    "y" "Happy birthday, I hope your day is splendid and that you are given reason enough to never let a smile leave your face."
    time hour 6 minute 2
    "m" "Oh, Yuri, you’re too much. I promise I will have a splendid day; after all, I’m spending some of it with you!"
    time hour 7 minute 5
    "y" "Ah, that’s true, though I’m far from your most important reason to smile, I’m sure."
    "m" "I promise, you’re my biggest reason to smile, Yuri. I’m looking forward to my time with you above everything else."
    "y" "Then that makes me happy, if a little embarrassed."
    "m" "I wouldn’t have it any other way~!"

    time day 23 hour 0 minute 0
    "m" "Happy birthday! I hope your day is wonderful and you never stop smiling~"
    "y" "Are you copying me?"
    "m" "Maybe~"
    "y" "Well then, they say imitation is the highest form of flattery, so I shall choose to take it as such, and not that you simply couldn’t be bothered to find something original to say."
    "m" "Then I’d call the operation a success~!"
    "y" "A success only possible by riding the coattails of those who came before, mind you."
    "m" "But a success nonetheless~"
    "m" "I need to sleep now, but I’ll see you in the morning!"
    "y" "I wouldn’t miss it for the world~"
    "y" "Sleep well, Monika."
    "m" "You too, Yuri!"    

    time day 30 minute 12 hour 14
    "m" "Hey, have you had that meeting with the coordinator yet?"
    "y" "I"
    "y" "That’s"
    "m" "I take that as a no?"
    "y" "Possibly"
    "m" "Do you want me to go with you?"
    "y" "No, I can handle it myself"
    "m" "I know you can, Yu, I just want to make sure you’re going to be okay doing it."
    "y" "Thank you"
    "y" "I appreciate your concern, but I don’t want to worry others over this."
    "m" "It’s no worry, as long as I know you’re alright."
    "y" "I will be fine, I just need some time to steel myself."
    "m" "I believe in you. I’ll be waiting by the gate; whether you go or not."
    "y" "Thank you" 

    time day 11 month 10 hour 11 minute 21
    "y" "Might you have some spare time during lunch this afternoon?"
    "m" "I might~"
    "y" "Wonderful. I shall meet you in the cafeteria."
    "m" "Of course! I’ll see you there~"    

    time day 21 hour 3 minute 4
    "y" "You’re probably asleep, but on the off chance that you are not, I wish to stress upon you the importance of sleep."
    "y" "Ergo, you should get some, if you haven’t already."
    time minute 19 hour 5
    "m" "I was sleeping, actually, which is what you should have been doing. Everything alright?"
    "y" "Social procedure dictates that I should respond with 'yes, quite', but such a statement would be a misrepresentation."
    "m" "You want to talk about it?"
    "y" "I would, else I’d have followed social procedure."
    "m" "Then I’ll give you a call, alright?"
    "y" "Mhm."  

    time day 1 month 11 hour 11 minute 3
    "m" "Hey, can you meet me outside my classroom when lunch starts? I’ve been asked to help move some things around and figured it’d be fun to have someone to talk to while I do."
    "y" "Of course, I’ll see you then."
    "m" "You’re the best. Please don’t feel obligated to help; it’s really nothing, I just thought it’d be nice to have someone to talk to as I rearrange the room."
    "m" "It’s for the culture festival next week, to be specific."
    "y" "I see, that does make sense. What is your class planning?"
    "m" "A book nook, actually. A place for people to relax and get away from all the hustle and bustle, with a collection of novels and the like provided by the school library."
    "y" "That does sound quite interesting; I’ll have to drop by on Monday."
    "m" "Please do! It’ll be quiet and calm, definitely your kind of place."
    "y" "However did you come up with such an idea, though? It’s quite removed from whatever most people would be expecting."
    "m" "It is, yes, but it was suggested by one of the girls in my class."
    "m" "The one with the pink, frizzy hair, you’ve probably seen her around"
    "y" "I believe I know the one; we shared a class last year. She consistently ranks second overall for grades, does she not?"
    "y" "She spends her time with Sayori outside of class."
    "m" "Sayori? Why does that name ring a bell?"
    "y" "She went to our middle school, was the athletics queen?"
    "m" "Oh! I know who you’re talking about now! The one who won track all three years"
    "y" "Yes, that one"
    "m" "What does she have to do with anything, though?"
    "y" "Nothing, as far as I’m aware. They’re just friends outside of class"
    "m" "Right"
    "y" "You simply mentioned the girl, and I was clarifying who you were referring to"
    "m" "Ah, right. Sorry, I guess I’m a little out of it today"
    "y" "Is everything alright?"
    "m" "Yeah, just"
    "m" "Just some stuff going on at home. Nothing major, I’m just a little exhausted"
    "y" "Perhaps you should get an early night tonight?"
    "m" "Exams are coming up, I can’t afford to take a night off"
    "y" "Exams are almost six weeks away. Surely you can afford to take a night to reset?"
    "y" "Your position at the top won’t be threatened by a single night."
    "m" "I hope not"
    "y" "I know how much pressure is on your shoulders, but worrying about it won’t make it easier on you."
    "y" "Slow down and learn to accept things as they are, and you’ll find yourself worked up less often and for less time."
    "m" "Yep, as always, when you’re right, you’re right."
    "m" "Thanks, Yuri. You’re a really good friend"
    "y" "I do my best~"
    "m" "See you shortly?"
    "y" "Of course"

    time day 7 hour 10 minute 11
    "y" "I’ve arrived at your class’ stall, but I can’t seem to find you"
    "m" "Ah, sorry Yuri! I’m actually working with the Debate Club for the first half of the day - Could I get a raincheck and spend some time with you around lunch?"
    "y" "Of course, I was simply confirming that I am not, in fact, blind."
    "m" "I’m really sorry, Yuri, I know how much you were looking forward to seeing me there. I’ll be helping out later, so you’re more than welcome to wait around and I’ll see you then?"
    "y" "Conversely, I might be convinced to attend the Debate Club’s showcase in around fifteen minutes? The one you’ve spent the better part of two weeks preparing for?"
    "m" "I"
    "m" "I don’t know what to say"
    "y" "I believe the words you are searching for go something along the lines of ‘thank you’?"
    "m" "Yes, they surely do"
    "m" "I would really appreciate it if you’d come by and listen in, but please don’t feel obligated to"
    "y" "Never. I do things because I choose to; not for any other reason"
    "m" "You are the light of my life, I swear"
    "y" "Indeed I am"   

    time day 16 hour 15 minute 22
    "y" "Might you be able to spare some time this afternoon?"
    "m" "Of course, what do you have in mind?"
    "y" "I wanted to visit a bookstore in town, but I’m not quite keen on the idea of going alone"
    "m" "Sure, I’ll come with you then. Usual place?"
    "y" "Yes, whenever you might be free"
    "m" "I’ll be there shortly then~"

    time day 27 hour 5 minute 41
    "y" "By any chance, might you be awake yet?"
    time hour 6 minute 32
    "m" "I am now, if that helps?"
    "y" "Very much so. I was hoping I might be able to borrow your textbook this afternoon"
    "m" "Why don’t we just organise a study session?"
    "y" "If it wouldn’t be too much trouble?"
    "m" "Of course not - You know me"
    "m" "I love hanging out with you, Yuri"
    "y" "Then yes, I would like that"
    "m" "Fantastic; I’ll see you then, if not sooner"
    "y" "Indeed!"

    time day 9 month 12 hour 19 minute 39
    "m" "Can you believe them?"
    "y" "Who?"
    "m" "My family. Ever since Cynthia came home from uni, they’ve gone back to pretending I don’t exist"
    "y" "I don’t understand, a few weeks ago you said you’d be happy if they did ignore you"
    "m" "Ignore me, yes, but not deny my existence!"
    "m" "I’m sorry, I shouldn’t be venting"
    "y" "No no, I understand. You’re upset and need to get it off your chest."
    "y" "If it will help, you’re more than welcome to continue."
    "m" "Thanks, Yu."
    "m" "It’s just"
    "m" "How am I expected to be the second heir if they refuse to teach me anything?"
    "y" "I expect that they don’t. You’re just a spare; Cynthia’s always been the favoured child."
    "m" "No, I know, but"
    "m" "It just hurts, knowing that the only way they’d ever give me any time of day is if something happened to her, yet they weigh all these expectations onto me, expecting me to know things I can’t possibly know because they haven’t taught me. What am I supposed to do, Yuri?"
    "y" "They place expectations upon you not because they see you as an heir, but because you are their child. Even if you aren’t the one they see at the head of the family, you’re still a child of the Rein family, and they won’t let you slack off because of that."
    "m" "But for what? Why do I have to go through all this if there’s nothing for me on the other side?"
    "y" "To build character?"
    "m" "Maybe."
    "m" "No, knowing them, that’s probably exactly what they see it as."
    "m" "Great."    

    time day 16 hour 15 minute 2
    "y" "How did your exams go?"
    "m" "Swimmingly, honestly. I don’t think I could have asked for much more than what I got."
    "y" "Even if you don’t know the results yet?"
    "m" "I was confident with every answer; you can’t ask for more."
    "y" "I see. The science questions toward the end provided more of a challenge than I was expecting, personally"
    "m" "The one about the falling tree?"
    "y" "Yes, that one in particular."
    "m" "You were supposed to use the time it took to fall, combined with the given density of the air to determine a coefficient of friction, and from that the speed of gravity and the amount of energy imparted onto the ground in newtons, then find the mass of the tree from the formula ‘Force equals Mass multiplied by Acceleration."
    "y" "Ah."
    "y" "I"
    "y" "I did not do that."
    "m" "What did you do?"
    "y" "I took the speed of the tree and the density of typical hardwood to find its mass?"
    "m" "Where did you get the density of hardwood?"
    "y" "I remember reading about it in a paper once"
    "m" "Right. I don’t think that would have applied here, considering the gravity was sitting at 11.42 metres per second per second."
    "m" "The density would probably be a little higher as a result of the elevated gravity"
    "y" "I see. That’s unfortunate"
    "m" "Don’t worry about it; you would have gotten most of the other ones right."
    "m" "No point stressing over it now, at least"
    "y" "You have a point."
    "y" "I suppose I’ll head home and reflect on my outcomes"
    "m" "Take care, alright? I’ll see you next week"
    "y" "I shall, yes." 

    time day 19 hour 8 minute 54
    "m" "Did you see the list of candidates running for the student council?"
    "m" "I’m glad I didn’t bother, oh my god"
    "y" "I haven’t yet, no"
    "y" "Is it an impressive list?"
    "m" "Impressive doesn’t begin to cover it"
    "m" "Chiaki, Riko, Gohan, Scarborough, Momo, Keita, Julie, Kana, Ai, Honoka and Ayame are probably the top contenders."
    "y" "Wait, all of them are running?"
    "m" "Yep"
    "y" "How many in total?"
    "m" "There’s about twenty running all up"
    "y" "I hope most of them are willing to settle for Prefect then"
    "m" "I hope so. It’d be a real bloodbath otherwise"
    time hour 12 minute 11
    "y" "You didn’t mention your friend Aika was running"
    "m" "Oh, you saw the board?"
    "y" "Just now, yes. Isn’t that going to make life hard for you?"
    "m" "We... we’ve talked about it"
    "y" "And?"
    "m" "I’m not going to stop her from running"
    "y" "If she runs and wins, she isn’t going to have time to lead a club"
    "m" "I know that"
    "y" "So what are you planning on doing?"
    "m" "I don’t know. Perhaps elevate someone from the year below and train them up?"
    "y" "Are you going to have the time and energy for that?"
    "m" "I don’t know"
    "y" "There’s no need to push yourself so hard, Monika"
    "y" "If you’re going to be stressing over this, shouldn’t you just not run for club president at the next election?"
    "m" "My parents would kill me"
    "y" "Yes, but wouldn’t you rather die on your feet than keeled over from exhaustion?"
    time minute 32
    "m" "Probably"
    "y" "All I’m asking of you  is that you think about it."
    "m" "I will"
    "m" "If Aika wins, perhaps it would be better to take a step back at the same time, let a fresh plate be set."
    "y" "What about if she doesn’t?"
    "m" "We’ll burn that bridge when we get to it."
    "y" "... I admit, you probably will"
    "m" "It’s what I’m best at" 

    time day 24 hour 11 minute 32
    "m" "Merry christmas, Yuri"
    "y" "Merry christmas to you, as well. Might you be looking for company to explore the snow-capped city with?"
    "m" "I might~"
    "y" "Then consider your evening booked"
    "m" "I would be most obliged to do so~"
    "y" "Might the fifth strike be to your liking?"
    "m" "Indeed, I believe it would be"
    "y" "Then consider it done, o Princess"
    "m" "I would have it no other way, o Lady Raven"

    time day 31 hour 22 minute 42
    "m" "How far away are you?"
    "y" "About three minutes, sorry"
    "y" "I was held up at home"
    "m" "That’s alright, I just don’t know for how long I’ll be able to hold this seat without seeming rude"
    "y" "I see"
    "y" "I can’t find you"
    "m" "Look up, I’m waving at you"

    time day 13 month 1 year 2017 hour 11 minute 48
    "y" "I might be running a touch late today, I apologise"
    "m" "Don’t worry about it, I’m not going to be bothered by a couple minutes"
    "y" "Yes, I’ve been asked to have a word with the girl - Natsuki, I believe - about her running for president"
    "y" "Scarborough wanted to know if she’d be willing to support her own bid and to band together to form a coalition of sorts."
    "m" "Really? Scarborough is taking this a lot more seriously than I expected, then. I imagine she’ll have asked quite a few of the candidates something similar."
    "y" "It appears a number of them are hoping to usurp the current lead in the polls."
    "m" "I have to give them credit, I don’t know if it’s possible."
    "m" "Momo’s already served on the Student Council, so she’s practically guaranteed a seat, even if she doesn’t win. Gohan’s probably going to settle for prefect, and I spoke to Riko the other day, and she mentioned that she’s probably resigned herself to a back seat, though she’s still going to run regardless."
    "m" "I honestly don’t think anyone’s going to be capable of seriously challenging Chiaki’s bid for SCP."
    "y" "Chiaki’s been in the public eye since we started and has been heavily involved in both the student council and the regular day-to-day life. I don’t think anyone else DESERVES it more than she does."
    "m" "On that, I think we agree."
    "m" "Let me know how your talk goes, but I’m not sure why you’re helping Scarborough if you’re planning on voting for Chiaki anyway."
    "y" "I’m open to having my mind changed; everyone willing to make a platform for themselves deserves a chance to speak on a level playing field."
    "m" "That’s very open-minded of you, Yuri. While I’m a little surprised you’re getting involved in the politics of it all, your reasoning is admirable."
    "y" "That’s how I see it, plain and simple. I want the best person for the role."
    "m" "Then I’ll support you in that"
    "y" "As always, your support means worlds to me."   

    time day 17 hour 14 minute 44
    "m" "Did you hear back from that girl in your class?"
    "y" "I did"
    "y" "You were right"
    "m" "I knew it"
    "m" "Alright, I’ll see you after school."
    "y" "Indeed"    

    time day 23 hour 6 minute 32
    "m" "Are you entering that extra credit exam this week?"
    "y" "Me? Certainly not."
    "m" "That’s alright, I was just hoping I’d have a friend sit it with me"
    "y" "Ah, I see"
    "y" "Perhaps I might be convinced to?"
    "m" "No, no, it’s alright. I think the girl with brown hair in my class was going to, I might ask her."
    "y" "Which one?"
    "m" "The quiet one with the fantastic grades"
    "y" "I’m not certain I’m familiar, but that’s alright"
    "m" "It’s all good, I’ve spoken with her before. She’s the one doing chemistry"
    "y" "I thought that was the girl with the pink hair?"
    "m" "She’s not in my class, though, she’s in yours."
    "y" "True enough"
    "y" "Either way, I see no problem with entering the competition if you have reason to do so"
    "m" "I was just hoping you’d do it with me, but it’s alright. I know it isn’t your strong suit"
    "y" "I simply feel the added work would not be worth the extra credit when I’ve already garnered enough points to pass the year."
    "m" "So have I, but those extra points do add up"
    "y" "Then by all means, go ahead"
    "m" "Will do"
    "m" "Enjoy your morning!"
    "y" "You too, Monika"   

    time day 7 month 2 hour 11 minute 11
    "y" "Have you seen the polls?"
    "m" "I sure have"
    "m" "I’m amazed, and that’s an understatement"
    "m" "Literally everyone’s talking about it"
    "y" "It’s the most obtuse upset in the school’s recent memory; I’d say it’s definitely warranted."
    "m" "Agreed, but isn’t it just incredible?"
    "y" "That someone can go from being relatively unknown to topping the polls in a matter of weeks?"
    "y" "I think the upset will come from her not winning the faculty’s vote."
    "m" "I think you’re right. For so long, I was convinced Chiaki would steamroll the vote, and it seems everyone else held that same opinion"
    "y" "The difference is, Chiaki deserves SCP. She’s been gunning for it for three years."
    "m" "And yet this Natsuki girl has stormed onto the scene to challenge that"
    "m" "Do you think we should support her?"
    "y" "I’m torn. Chiaki’s my friend, as she is yours, and she’s spent every waking moment of the past three years preparing for this"
    "y" "In the end, I will side with her"
    "m" "In the end, I think most people will; it’s just a little refreshing to see someone make such waves at such a late stage. Her command of the debates lately has been a sight to see"
    "y" "If the faculty allows her to sit on the council, I’d like for her to hold the vice-presidency."
    "m" "I think that would be a happy ending to all this, absolutely"  

    time day 20 hour 12 minute 33
    "y" "Did you want to meet for lunch today?"
    "m" "Oh, sorry, I’m actually meeting with Aika today"
    "y" "Ah... you’re discussing it?"
    "m" "It seems so."
    "y" "Good luck."

    time day 3 month 3 hour 7 minute 31
    "y" "I can’t take this silence anymore, Monika"
    time hour 9 minute 57
    "y" "I’m not asking you to talk to me, just to listen."
    "y" "I’ve known you for five years, and this is the longest we’ve gone without talking."
    "y" "I’ve talked with your sister over the past two weeks more than I’ve talked to you."
    "y" "I know that you’re trying to do this... what, lone wolf thing, but this isn’t like you."
    "y" "Just... tell me what you’re trying to do, and I’ll help you."
    time hour 21 minute 22
    "m" "I’m trying to start a club."
    "m" "Miss Uiharu is willing to lend her signature, though she probably won’t have much involvement beyond that."
    "y" "Then I’ll help you."
    "m" "Yuri, I-"
    "m" "This is something I need to do for myself."
    "m" "Please understand."
    "y" "I want to, I do, but"
    "y" "It feels like you’re blocking me out for the sake of it. Why is it so important to you that you do this alone?"
    "m" "Because I need to prove that I can do things with my own hands, Yuri. I know you probably won’t get it, but..."

    time day 8 hour 21 minute 11
    "m" "Have you got a minute, if you’re still up?"
    "y" "Of course."

    time day 9 hour 5 minute 38
    "y" "I won’t be at school today, there’s... well, you know."
    time hour 6 minute 3
    "m" "Of course, I’ll take notes for you."
    "y" "I appreciate it."
    time hour 17 minute 11
    "m" "I’m outside, did you want me to bring them in?"
    "y" "No, please just leave them at the door. It’d be better for your safety."
    "m" "Alright"

    time day 14 hour 16 minute 45
    "y" "How do you feel?"
    "m" "I feel like this was my worst round of exams yet."
    "y" "I’m sure you’ll be fine, don’t stress over it."
    "m" "Thanks, Yu"    

    time day 18 minute 11 hour 12
    "y" "I’m amazed."
    "m" "Oh yeah, that’s definitely the word for it."
    "m" "My parents are going to kill me."
    "y" "Well, yes, but it’s the first time someone in the grade has bested you since middle school, and to think it was a newcomer in their first term of holding a position on the Student Council?"
    "m" "Yes, yes, please, rub it in."
    "y" "That’s not what I mean and you know that."
    "m" "I know, I’m just sore."
    "y" "If anything, it’s a challenge."
    "m" "Right now, a challenge is the last thing I need..."
    "y" "Maybe it’s not? Maybe that’s exactly how you get out of your rut?"
    "m" "Hm."
    "m" "Actually, I think you might be right."
    "m" "Oh my god, I think you’re right!"
    "m" "I think you’re onto something!"
    "y" "... Am I?"
    "y" "I mean yes!"

    time day 19 hour 16 minute 22
    "m" "I knew it!"
    "y" "Knew what?"
    "m" "You were right!"
    "y" "Right on what account, exactly?"
    "m" "I asked that girl to join my club."
    "y" "Pardon?"
    "m" "Well, we need four members to form a club, no?"
    "y" "Yes...?"
    "m" "Now, we have three!"
    "m" "I mean, we haven’t decided on anything yet, and she didn’t exactly agree, but it’s a start."
    "y" "Wait, three?"
    "y" "Who else?"
    "m" "Well there’s me, you, and now this Natsuki!"
    "y" "Mon, I never said I would join-"
    "m" "..."
    "m" "I’m sorry for making assumptions."
    "y" "But I never said I wouldn’t!"
    "m" "No, no, I won’t force you."
    "y" "No I’m happy to-"
    "m" "Yuri, please, I don’t want you joining just out of pity or anything."
    "m" "I’ll find another way."
    "y" "If that’s how you feel."   

    time day 11 month 4 hour 8 minute 44
    "m" "I’m at the mall, near the front entrance."
    "y" "I’ll be there in just a moment."

    time day 30 hour 15 minute 31
    "y" "I’ve prepared the work you wanted me to, and I’m bringing them to the butler at the gate."
    time minute 56
    "m" "Thank you"

    time day 2 month 5 hour 7 minute 8
    "m" "Did you sleep last night?"
    "y" "No, not a wink."
    "m" "Aha, that storm really was something, wasn’t it?"
    "y" "Indeed. I’m not quite sure how I’m going to go at school today..."
    "m" "I trust you’ll be alright! I’ll sit next to you so we can study together."
    "y" "You’re too kind."
    "m" "Am I? I feel like that’s the least I could do."
    "y" "Yes, you are..."
    "y" "I appreciate it."
    "m" "Naturally~"    

    time day 17 hour 12 minute 12
    "y" "Did you want to meet for lunch today?"
    "m" "Sure, but you could have asked me when we spoke earlier."
    "y" "I didn’t want to be a bother."
    "m" "Yuri, you’re not a bother. I’d love to have lunch with you, anytime, anywhere."
    "y" "Thank you, Monika."
    "y" "I’ll meet you in the music room, assuming you’re already there?"
    "m" "Yes, I am. Feel free to join me."
    "m" "And, you don’t have to ask. You can just show up; you know where I’ll be."
    "y" "I know, but sometimes I feel like asking."
    "m" "You’re an enigma, my friend~"
    "y" "Just the way you like it~!"
    "m" "True true~!"   

    time day 21 hour 18 minute 21
    "m" "I just spoke to Natsuki, and well"
    "y" "She’s a little odd, isn’t she? Excitable, I believe the word is."
    "m" "Sure, yeah. It almost feels like she’s overcompensating for something."
    "y" "She’s new to her role, it might be that she’s trying to feel like she fits in."
    "m" "That’s exactly what it feels like, yeah."
    "y" "So, what did she say?"
    "m" "She’s got her hands full, so she’ll reconsider possibly next term."
    "y" "That does make sense, I had a feeling that would be the case."
    "m" "Well..."
    "m" "I guess that doesn’t leave me with much choice."
    "y" "You still want me to give you a few months?"
    "m" "I do, yeah."
    "m" "I’m sorry I’m being stubborn about this, but"
    "y" "The more I think about it, the more I think I get it."
    "y" "Just promise me that you’ll ask if you need it."
    "m" "I will."

    time day 7 month 6 hour 15 minute 31
    "y" "Did you want to join me for study today?"
    "m" "Actually, I’ve got the day off cram school, so that would be fantastic. Meet at the cafe north of the bridge?"
    "y" "Really? That’s different."
    "m" "Cynthia recommended it to me when she was in town last month. I really wanted to try it out."
    "y" "Then yes, I’ll meet you there."
    "m" "See you there!"    

    time day 15 hour 5 minute 32
    "y" "Monika"
    time hour 5 minute 2
    "m" "Everything alright?"
    "y" "Oh, yes, everything is fine, please ignore that. I’d forgotten I’d sent it."
    "m" "Alright?"
    "y" "It was nothing, I swear."
    "m" "Okay, sure."
    "y" "It was!"
    "m" "I believe you!"
    "y" "Oh, good"
    "y" "Texting is hard sometimes, sorry. This is why I prefer our calls."
    "m" "It’s alright, Yuri. If you needed me, you could have just called me, you know?"
    "y" "Yes, I know"
    "y" "But nevermind."
    "y" ":)"
    "m" "Okay?"
    "m" "You’re an odd one, my friend."
    "y" "Yes, indeed..."

    time day 28 hour 16 minute 55
    "m" "Yuri!"
    "m" "Someone showed up today!"
    "y" "I knew it would happen eventually!"
    "y" "Who was it?"
    "m" "A girl from my class, Sayori. She’s cheerful, friendly and upbeat - She might draw in other members!"
    "y" "That sounds wonderful! I’m so happy for you!"
    "m" "Thanks, too"
    "y" "For believing? Of course."
    "m" "Well yes, that too, but for trusting me."
    "y" "Naturally. I knew it would work."
    "y" "It just needed some time."

    time day 2 month 7 minute 45 hour 5
    "m" "Yuri, did you hear the knees?"
    "y" "I believe I did - You got a new member?"
    "m" "Natsuki is one of Sayori’s friends, and she managed to convince her to join!"
    "y" "So does that mean..."
    "m" "With three members, we have the minimum for a club, so yes, I think my silly little goal has been reached."
    "y" "It wasn't silly, Mon. You wanted to see if it was possible for you to form a club without support. If I’d been there, you'd only have needed a single other person."
    "m" "Thank you"
    "y" "It's what I do, Monika."
    "y" "I’ll see you at club tomorrow?"
    "m" "Yes, you will, aha~"
    "y" "I've been waiting months to say that~"
    "m" "You're adorable"
    "y" "The contents of this message have been deleted by the author"
    "m" "?"
    "y" "Don't worry about it, I just accidentally sent something"
    "m" "Alright"

    time day 14 hour 17 minute 15
    "y" "Hey Mon, I just"
    "y" "I don't know how I feel about the two new girls"
    "m" "What do you mean?"
    "y" "They're like"
    "y" "I don't know how to describe it. The aura I get from them is really fake."
    "m" "Yuri, I know you're not good around new people, but this is good for both of us. I just don't want you projecting that onto two people we've just met."
    "y" "No it's not that"
    "y" "It's that, well"
    "y" "I can't quite put my finger on it"
    "m" "Yuri, you're just apprehensive about everything. I promise they're good people."
    "y" "No, I trust you, I do"
    "m" "Then why are you still pushing this?"
    "m" "What's this really about?"
    "y" "It's nothing, I swear!"
    "m" "Yuri, if it was nothing you wouldn't have brought it up. I know you, you're my best friend."
    "y" "Yeah."
    "y" "I know I am."
    "m" "What is it?"
    "y" "Please stop pushing."
    "m" "Alright, I’ll drop it, but I’m just worried about you, is all."
    "y" "I’m alright."
    "m" "I trust you, Yuri. You know that."
    "y" "I do"

    time day 4 month 8 hour 6 minute 47
    "y" "Did you want to meet up for lunch today?"
    "m" "Sorry Yuri, I’m actually meeting with Sayori for a study session. You’re welcome to join us?"
    "y" "No, it’s fine, I’ll go find something else to do"
    "m" "You can join us, you know."
    "y" "I know I can"
    "m" "So why don’t you? You realise both of them like you, right?"
    "y" "I know"
    "m" "So why brush them off?"
    "m" "They want to be your friend, especially Natsuki. You should see how awkward she looks in clubtime when she looks at you!"
    "m" "It’s sweet how much she wants to take that step."
    "y" "I know it is, but"
    "m" "But what?"
    "y" "I don’t know"
    "y" "It just feels like"
    "m" "Like they’re taking me away from you?"
    "y" "Monika, I"
    "y" "I can’t believe you think that of me"
    "m" "Well, what do you want me to think?"
    "m" "Please, give me something else to think."
    "y" "I’m just worried, okay?"
    "m" "I know you are, but that worry is misplaced. Both of these girls are just trying to get through their last year of school; there’s nothing nefarious going on here."
    "m" "I just wish you’d see that."
    "y" "Alright. I’ll talk to them tomorrow."
    "m" "You will?"
    "y" "I’ll try."
    "m" "Do. There’s no try."
    "y" "I can’t believe you"
    "m" "What, that I can quote a movie?"
    "y" "No, that you can quote a movie poorly."
    "m" "Ouch"
    "y" "It wasn’t an insult, it’s just"
    "y" "Nevermind"
    "y" "Maybe I’ll show you what I mean sometime"
    "m" "Sure! I’d love to know"
    "y" "Yeah? Alright, I’ll make some time. Maybe over the weekend?"
    "m" "Can’t do this weekend, we’re busy."
    "m" "Family trip."
    "y" "But Cynthia’s not going to be home for like four months."
    "m" "Yeah."
    "m" "It’s complicated"
    "y" "I see"
    "y" "Well, good luck. You know where I’ll be if you need me."
    "m" "That I do" 

    time day 19 hour 6 minute 25
    "m" "Hey Yuri, I was wondering if you wanted to get lunch today?"
    "y" "You could have just called me"
    "m" "I could have, but you’re often busy getting ready this time of morning."
    "y" "That’s what you consider considerate?"
    "m" "Yes?"
    "m" "Yuri, if there’s a problem, please just say it. We’ve been friends forever, and I don’t want whatever this is ruining that."
    "y" "It’s nothing."
    "m" "Are we really having this conversation again? You’ve hardly spoken to me over the past month - what is it that you want me to do?"
    "y" "It’s nothing!"
    "y" "Just me being stupid."
    "m" "Don’t talk about yourself that way!"
    "y" "This message has been deleted by the author."
    "m" "Yuri, of course I would pay attention to you! Do you think you aren’t interesting just when you’re being yourself?"

    time day 21 hour 23 minute 50
    "y" "Yes."

    time day 22 hour 5 minute 45
    "m" "Then I’m sorry I’ve ever made you feel that way. You’re genuinely the most important person to me, Yuri; You’re my best friend."
    time hour 18 minute 50
    "y" "I know."
    "m" "So why are you pushing me away like this?"
    "y" "Because you don’t need me."
    "m" "Of course I do! I can’t understand what you’re saying, Yu."
    "y" "No, I expect you can’t."
    "y" "Just ignore me"
    "m" "You know I won’t do that."
    "y" "Well, that’s your only option"
    "m" "No it isn’t. If I have to fight to keep you around, you know I will."
    "m" "All of this is so unlike you"
    "y" "Well"
    "y" "Just forget it"
    "y" "I’m over it"
    "m" "Over what?"
    "y" "Everything"
    time hour 6 minute 31
    "y" "You didn’t have to call me"
    "m" "I felt like I did"
    "m" "If you don’t trust me, then that means that I’ve done something to erode that trust."
    "y" "Now you’re starting to sound like me"
    "m" "Maybe I am"

    time day 30 hour 20 minute 24
    "y" "I’m guessing the last couple days have been your handiwork?"
    "m" "Red handed, aha~!"
    "y" "There are many things I could say. I could be upset that you meddled with my life and how things are, but"
    "y" "Just"
    "y" "Thank you"
    "m" "I know, you don’t have to say it."
    "y" "But you deserve to hear it"
    "y" "So thank you."
    "y" "You’ve genuinely done me a service, and both of these girls seem to be genuine people, unlike my initial impression."
    "m" "See? What did I tell you?"
    "y" "I suppose I had other ideas based on the fact that one of them is a member of the student council and the other is, well"
    "y" "I’m actually not sure how to categorise Sayori"
    "m" "Maybe that’s a sign that you don’t have to?"
    "m" "Can’t she just be your friend?"
    "y" "yeah."
    "y" "yeah, I like that"
    "y" "Friend."
    "m" "Now you have two more you can lean on, yeah?"
    "y" "I do now."
    "y" "Thank you."
    "m" "You should go hang out with them this weekend"
    "y" "Me? With them?"
    "m" "Why not? I’m away, so it’s the perfect chance for you"
    "y" "I suppose so..."
    "y" "Then I’ll let you know how it goes"
    "m" "Please do~!"

    time day 2 month 9 hour 15 minute 10
    "y" "I spent the day with Sayori and Natsuki"
    time minute 34
    "m" "How’d it go?"
    "y" "You were absolutely right"
    "y" "About everything"
    "y" "I’m sorry I doubted you"
    "y" "But it seems like, well"
    "y" "I don’t know if it’s my place to comment, actually"
    "y" "So I won’t"
    "m" "Aha, alright, as long as you had fun~"
    "y" "I genuinely did, thank you."
    "y" "I’ll heed your advice more carefully from now on."
    "m" "That’s my girl~"   

    time day 20 hour 7 minute 41
    "y" "Did you want to get lunch today?"
    "m" "That sounds fantastic. I’ll meet you in the cafeteria?"
    "y" "Splendid"

    time day 23 hour 10 minute 23
    "m" "I’ve got a free day today, did you want to grab some lunch in town?"
    "m" "If not, I could do dinner?"
    "y" "Yes!"
    "y" "It feels like forever since we last spent time outside of school."
    "m" "It does, doesn’t it? With everything ramping up, it was bound to happen eventually."
    "m" "The usual place?"
    "y" "That sounds wonderful. 11:30?"
    "m" "That works!"
    "y" "See you there."
    "m" "See you there!"    

    time day 7 month 10 hour 7 minute 38
    "m" "Hey Yuri, I wanted to chat about yesterday. Would you mind if I gave you a call today?"
    "y" "Not today"
    "m" "Alright, tomorrow?"
    "y" "No, not tomorrow either"
    "m" "Well, set a time, and I’ll try and work around it."
    "y" "No"
    "m" "I don’t understand."
    "y" "I told you this would happen."
    "m" "That what would happen?"
    "y" "That all of this would happen. That they were bad news."
    "y" "I want to like them, I do, but"
    "y" "How can I?"
    "m" "Because they make mistakes? Like you do?"
    "y" "You’re siding with them?"
    "m" "I’m not siding with anyone, Yu. You know that."
    "y" "Why have we fought more in the past few months than in the past few years, Monika?"
    "m" "I don’t know."
    "y" "I think it’s because of the company you keep."
    "y" "You’re changing."
    "y" "And it’s not for the better."
    "m" "Everyone changes, all the time."
    "m" "Your role in life is to keep up."

    time day 19 hour 20 minute 29
    "y" "I wanted to apologise again"
    "m" "It’s alright."
    "m" "I apologise too, I should have handled the whole thing differently."
    "m" "I don’t want to lose my best friend over something so trivial."
    "y" "Agreed."
    "y" "But"
    "y" "Thank you for still considering me as such."
    "m" "Naturally~"    

    time day 22 hour 12 minute 3
    "m" "Lunch?"
    "y" "Read my mind."
