init python:
    def get_mc_s_gc_name():
        return "Sayori" if pov_key == "mc" else _("Mel")

init phone register:
    define get_mc_s_gc_name:
        icon ConditionSwitch(
            "pov_key =='s'", phone.asset("mc_icon.png"),
            "True", phone.asset("sayori_icon.png")
        ) 
        key "mc_s"
        add "mc" add "s" as mc_s_gc
 
    time month 1 day 26 year 2013 hour 14 minute 31
    "mc" "Ah!"
    "s" "Boo!"
    "mc" "Ah!"
    "s" "Ehehehe, how's the new phone?"
    "mc" "Maybe you should come over and find out! It's got so many cool new features!"
    "mc" "Smartphones are so cool!"
    "s" "Alright! I'm gonna be around in a sec, just gotta put the washing machine on!"

    time minute 55
    "s" "On my way now!"

    time day 27 year 2013 hour 9 minute 12
    "mc" "Hey Sayori"
    "mc" "Guess what"
    "s" "You got a new toy?"
    "mc" "Better"
    "s" "... I dunno"
    "mc" "Guess what arrived today in the mail"
    "s" "NO WAY"
    "mc" "YES WAY"
    "s" "GIVE ME TEN SECONDS"

    time hour 22 minute 19
    "s" "Whyyyyyyyy"
    "mc" "Right???"
    "mc" "I wanted to keep watching..."
    "s" "Your mom is so laaaaame!"
    "mc" "Tell me about itttt"
    "s" "We finally got the box set and now she makes me go home before we finish?"
    "mc" "I mean, it is pretty late, and we were being loud the entire day..."
    "s" "Stop making good points! I wanted to finish!"
    "s" "WE HAD TWO EPISODES TO GO"
    "mc" "I know..."
    "mc" "Wanna come over tomorrow and watch the rest?"
    "s" "I'll wake you up"
    "mc" "You better not"
    "s" "You can't stop me"
    "mc" "I can lock the door"
    "s" "I have a spare key"
    "mc" "I can lock my bedroom door"
    "s" "Got one for that, too"
    "mc" "Uhh"
    "mc" "I'll tell my mom you're coming in at like 5am again"
    "s" "No you won't"
    "mc" "I'll..."
    "mc" "Lock myself in the bathroom"
    "s" "All night?"
    "mc" "Yes"
    "s" "Just because you don't want to wake up early to watch the last two episodes"
    "mc" "No, I do, but you always get me up at like 4am and that's so earlyyyy"
    "s" "Coward"
    "mc" "... Fine."
    "mc" "But if we get in trouble, I'm blaming you."
    "s" "See you at 4am!~"
    "mc" "Yeah, yeah. I'm gonna get some sleep, okay?"
    "s" "No you aren't"
    "mc" "What makes you say that?"
    "s" "Look outside~"

    time hour 23 minute 56
    "mc" "Okay, for real, I'm getting sleep now."
    "s" "Talk to you tomorrow!"
    "mc" "You absolutely will!"
    "s" "Night night, Melly!"
    "mc" "Night, Sayori"
    "mc" "Sleep well"
    "s" "You too!"

    time day 28 hour 12 minute 41
    "s" "Heeeey~"
    "mc" "What's up?"
    "s" "Come to the park after you're finished with lunch!"
    "mc" "Why?"
    "s" "I got a new game we gotta play!"
    "mc" "What's that?"
    "s" "Just come!"
    "mc" "Okay, okay"
    "mc" "It'll probably be a little while, my dad's home from his business trip"
    "s" "Awwww"
    "s" "Fine, I'll wait"
    "s" "You better not be late!"
    "mc" "I know, I know"
    "mc" "I'll let you know when I'm on my way"
    "s" "See you soon"
    "mc" "Sorry! On my way now"
    "mc" "He just talked and talked and talked"
    "s" "Oh good! I thought you forgot!"
    "mc" "Never"

    time day 28 hour 15 minute 15
    "mc" "By the tree"
    "s" "Which one?"
    "mc" "I'm waving at you"
    "s" "Whereeeee"
    "mc" "Stop"
    "mc" "Turn to your left"
    "mc" "There you go"

    time month 2 day 1 hour 5 minute 50
    "s" "Oiiii"
    "s" "I know you're awake"
    "s" "Melly"
    "s" "I will throw more rocks at your window"

    time day 3 hour 18 minute 41
    "mc" "Check this out"
    "s" "What?"
    "mc" "Look out your window"

    time day 11 hour 13 minute 25
    "s" "Where are you?"
    "mc" "Grabbing lunch, why?"
    "s" "Because I'm lonely"
    "mc" "Go hang out with your friends then"
    "s" "Huh?"
    "mc" "You heard me"
    "s" "What'd I do?"
    "mc" "You didn't walk to school with me"
    "s" "I had to go early for practice"
    "mc" "I would have walked earlier"
    "s" "I didn't want to be a bother"
    "mc" "Well you were"
    "s" "I didn't mean to be"
    "s" "All I did was organise to see one of my friends before school to help me practise"
    "mc" "No, you went and saw Kaito to practise"
    "s" "You're unbelievable sometimes"

    time hour 15 minute 45
    "mc" "Hey"
    "s" "Hey"
    "mc" "I'm sorry about before. I don't know what came over me"
    "s" "I know you are"
    "s" "I should have told you I was leaving early, so you didn't wait up and end up late waiting for me to walk out the front door when I wasn't even home"
    "mc" "Even so, I shouldn't have been that angry"
    "s" "Call it even then?"
    "mc" "Yeah"
    "s" "Let's get ice-cream on the way home then"
    "mc" "Sure"
    "s" "See you then"
    "mc" "Sure will"

    time day 12 hour 17 minute 51
    "mc" "Wanna come over for dinner?"
    "s" "What time?"
    "mc" "Now?"
    "mc" "My mom went out today and hasn't come home, and my dad just left. I think he's upset"
    "s" "Why's that?"
    "mc" "I dunno. Maybe he's upset that she's never home"
    "s" "Well maybe she should be home more then"
    "mc" "If they talked about it, maybe it would work yeah"
    "mc" "But they don't talk anymore. Every time my dad comes home from his trips, my mom leaves more often"
    "s" "You think they aren't getting along?"
    "mc" "Maybe. They keep telling me to not worry though"
    "mc" "Could just be that they're wanting time apart"
    "s" "Weird. Whenever I think about the people I like, I couldn't imagine spending time apart from you"
    "mc" "Right? If I was going away for work all the time, I'd want to spend all the time I have at home with you"
    "s" "Absolutely!"
    "mc" "You ever"
    "mc" "You ever think maybe they're unhappy?"
    "s" "I dunno"
    "mc" "I think sometimes they don't like spending time with each-other, and when they do, it makes them upset"
    "mc" "It's only started happening recently, so maybe it's just a phase"
    "s" "Like that time you spent away from me last year"
    "mc" "I mean look"
    "mc" "I wanted"
    "mc" "Huh"
    "mc" "I don't even remember what I wanted anymore"
    "s" "Yeah"
    "s" "Over time it just stopped mattering"
    "mc" "Maybe I should tell them that"
    "mc" "Whatever's bothering them, it'll go away with time"
    "s" "Sounds good"
    "mc" "But yeah, come over for dinner and we can hang out"
    "s" "I'll be there soon, just gotta catch up on some homework"
    "mc" "Want a hand? We can study together"
    "s" "You say that, but you never even need to put work in to get good grades"
    "mc" "I won't distract you this time, promise"
    "s" "Sure sure"
    "s" "I'll be there shortly"

    time day 13 hour 14 minute 32  
    "mc" "Can I crash at yours tonight?"
    "s" "Sure, why?"
    "mc" "Long story"
    "s" "Wanna walk home together then?"
    "mc" "Yeah, definitely"
    "s" "Mind if someone joins us?"
    "mc" "Who?"
    "s" "No-one special, just a friend of mine"
    "mc" "I suppose that's fine"
    "s" "You can say no"
    "mc" "No it's okay"
    "s" "If something's bothering you, just tell me"
    "mc" "It's Kaito, isn't it?"
    "s" "What if it is?"

    time minute 58  
    "mc" "Fine, I'll meet you outside the gate"

    time day 19 hour 19 minute 41
    "mc" "Hey"
    "s" "What's the happs"
    "mc" "That thing you said about your birthday party over the weekend?"
    "mc" "I'm sorry I was a little"
    "mc" "Well, I wasn't very nice"
    "s" "Weren't you?"
    "s" "You didn't really seem out of character to me"
    "mc" "That is cutting"
    "s" "Ehe~"
    "s" "But for real, it's okay"
    "s" "I'm gonna invite a whole bunch of people, and I just wanted to make sure you were okay with that"
    "mc" "Of course I'm okay with that, it's your party"
    "s" "That's not how it seemed to me"
    "mc" "I know, I just"
    "mc" "I felt bad"
    "s" "You mean, 'Now I feel bad'"
    "mc" "Yeah"
    "s" "It's okay to be upset when things don't go your way"
    "s" "Just remember that we still have all year to spend together"
    "s" "Think about this year"
    "s" "We haven't spent a day without seeing each-other yet"
    "mc" "Yeah"
    "s" "What is it?"
    "mc" "It's nothing"
    "s" "It's clearly not nothing"
    "mc" "No, it is, I swear"
    "mc" "I'm totally fine"
    "mc" "Look, I'll prove it"
    label "File sent"
    "s" "You do look pretty fine"
    "mc" "See?"
    "s" "I'll admit, yeah"
    "mc" "So just... I'm sorry"
    "s" "I already told you it's okay"
    "s" "You don't need to apologise for everything, Melly"
    "s" "I know you sometimes say things you don't mean"
    "mc" "Sometimes I just wish I filtered things before I blurt them out"
    "mc" "Maybe what I really need is a good kick to get me to not say stupid stuff" # im stuff
    "s" "What sort of kick? I'll kick you"
    "mc" "Yeah you will"
    "s" "Huh?"
    "mc" "I mean, yeah, you will kick me. It might work"
    "s" "I'll give it a go next time you say something stupid"
    "mc" "Aight, I'll hold you to that"
    "s" "And I'll hold you to the wall"
    "mc" "Huh?"
    "s" "So I can kick you?"
    "mc" "Right"
    "s" "What did you think I meant?"
    "mc" "Uhh"
    "s" "You're such a weirdo sometimes"
    "mc" "Yeah, I am"
    "s" "So my phone's about to die, so I gotta go plug it in"
    "mc" "Awww"
    "s" "Wanna morse code through the window?"
    "mc" "Hell yes"

    time month 3 day 1 hour 23 minute 44
    "mc" "Can't sleep?"
    "s" "Yeah"
    "mc" "I saw your curtains move"
    "s" "Why were you looking at my curtains?"
    "mc" "Cuz I was hoping you'd be up"
    "s" "What's on your mind?"
    "mc" "I dunno, just..."
    "mc" "Couldn't sleep"
    "s" "I mean, my birthday's coming up. It's gonna be fun"
    "s" "Were you thinking about what to get me?"
    "mc" "You kidding? I've had your present for weeks"
    "s" "Really? I'm gonna come over tomorrow and find it"
    "mc" "Wait no-"
    "s" "Kidding"
    "s" "I know you worked hard picking something out for me, I'm not gonna spoil the surprise"
    "mc" "Oh good"
    "s" "Chill, hey? You take everything so seriously sometimes"
    "mc" "Yeah"
    "s" "Is that why you're up?"
    "mc" "Maybe"
    "s" "Wanna talk about it?"
    "mc" "I dunno"
    "mc" "Sometimes I wonder why I take everything so seriously"
    "mc" "It's not like I want to"
    "mc" "Everything just sorta happens, and then I gotta deal with it"
    "s" "I mean, that's the same for everyone, right?"
    "s" "We all have problems"
    "mc" "But most people just like"
    "mc" "Their problems don't make them think"
    "s" "I dunno, I'm always thinking"
    "s" "Always and always"
    "mc" "Yeah?"
    "s" "So maybe it isn't just you, but you just feel a little alone and lost in your problems sometimes"
    "mc" "Maybe"
    "mc" "Why though?"

    time day 2 hour 0 minute 0
    "mc" "I didn't ask to think so much"
    "s" "I guess it's cuz you're smart"
    "s" "You're heaps smarter than me, so you think harder"
    "mc" "Don't say that, you're smart"
    "s" "Am I?"
    "s" "Or are you just saying that to make me feel better?"
    "mc" "I know you're smart, just not the same way other people might be"
    "mc" "You are so good with people, and you can fix arguments, you just make everyone's lives better"
    "s" "Yeah"
    "mc" "I can't do any of that"
    "mc" "So yeah, you're smarter than me"
    "mc" "I just get better grades sometimes because I really like studying sometimes"
    "mc" "Just gotta be in the right mood"
    "s" "I suppose"
    "mc" "Don't put yourself down because you aren't getting amazing grades"
    "mc" "There are plenty of people who don't get good grades"
    "s" "Yeah, but you don't talk to any of them"
    "mc" "That's not a fair comparison, I don't talk to anyone"
    "s" "So you admit it"
    "mc" "Grr"
    "s" "Gotcha~ Ehe"
    "mc" "That's mean"
    "mc" "I was trying to make you feel better"
    "s" "You did"
    "s" "You always make me feel better"
    "mc" "Do I?"
    "s" "Always"
    "mc" "Now you're just trying to make me feel better"
    "s" "Nope, it's the truth"
    "s" "You're my favourite person, you know?"
    "s" "My best friend"
    "mc" "Yeah"
    "mc" "I know"

    time minute 41
    "s" "Why do you clam up like that?"
    "s" "I dunno, you just feel like..."
    "s" "Like every time I talk about something cool or fun about you, you just"
    "s" "Brush me aside, or dismiss it"
    "s" "I'm a little worried about you, you know?"

    time hour 7 minute 11
    "mc" "Sorry"
    "mc" "I fell asleep"

    time minute 50
    "s" "No you didn't"
    "s" "I can see through your window, dummy"

    time hour 18 minute 41
    "mc" "Hey"
    "mc" "Thanks for today"
    "mc" "I guess I just needed to hang and clear my head"
    "s" "Yeah, I know"
    "s" "Sometimes the thoughts get really loud, hey"
    "mc" "Yeah. Hard to hear myself think"
    "mc" "Hard to breathe"
    "mc" "It's like I'm drowning, all the time"
    "mc" "But I don't wanna be"
    "mc" "I wanna learn to swim, Sayori"
    "s" "Yeah"
    "s" "Have you talked to anyone about it?"
    "mc" "Nah"
    "s" "Maybe you should?"
    "mc" "..."
    "mc" "I don't wanna bother them"
    "s" "You're talking to me about it"
    "mc" "Oh"
    "mc" "Sorry"

    time hour 19 minute 32
    "s" "Hey, I'm not upset, so don't apologise"
    "s" "Just like"
    "s" "I don't want to see you unhappy, is all"
    "mc" "Well"
    "mc" "I guess lately, I've sorta always been unhappy"
    "s" "Oh"
    "mc" "Always, except when I'm around you"
    "s" "Oh"
    "s" "Wanna hang out tomorrow and talk about it?"
    "mc" "Maybe"
    "s" "My place, 7am sharp"
    "mc" "If I can wake up"
    "s" "I'll come get you"
    "mc" "No, it's okay"
    "s" "No, that wasn't a question"
    "s" "I'll be there to wake you up"
    "mc" "No, it's fine"
    "s" "Melly"
    "s" "I'm worried about you, okay?"
    "mc" "Yeah"
    "s" "So I'll be there tomorrow morning"
    "mc" "Okay"
    "s" "Love you"
    "mc" "Yeah"
    "s" "Sleep well, bestie"
    "mc" "Yeah"

    time day 7 hour 0 minute 0
    "mc" "Happy birthday"
    "s" "Thanks!"
    "s" "I'm glad you were the first to wish me a happy birthday"
    "s" "Makes me thankful I waited up for it"
    "mc" "Well, I almost jumped the gun and sent it a couple seconds early haha"
    "s" "It would have still meant the same to me"
    "s" "I just would have been happier even sooner"
    "mc" "Hah, true"
    "mc" "So this weekend is your party"
    "s" "Sure is!"
    "mc" "You got heaps of people coming?"
    "s" "Sure do!"
    "mc" "Cool"
    "mc" "Wanna walk to school together tomorrow?"
    "s" "Absolutely"
    "s" "Wanna get ice-cream on the way home?"
    "mc" "Yeah"
    "s" "Sounds like a plan!"
    "s" "I'll see you bright and early then"
    "s" "Don't be late this time, okay?"
    "mc" "I'll try"
    "s" "Do or do not; there is no try"
    "mc" "Yeah yeah"
    "mc" "I'll be there"
    "s" "Ehe"
    "mc" "Sleep well, Sayori"
    "mc" "Love you"
    "s" "Love you too!"

    time day 10 hour 19 minute 11
    "mc" "Did you have a good time?"
    "s" "Yeah"
    "s" "That was real unexpected though"
    "mc" "No kidding"
    "mc" "But hey, could have gone worse"
    "s" "True. It was really awkward having to turn him down in front of all those people"
    "s" "I feel a little bad"
    "mc" "Don't, he kinda asked for it when he did it publicly. Makes it harder to say no"
    "s" "True"
    "mc" "So it's probably better this way"
    "s" "Yeah, I suppose. Still, I can't believe you!"
    "mc" "Hm?"
    "s" "Why did you get me that?"
    "mc" "Because I could?"
    "s" "No, I mean"
    "s" "Ah, forget it"
    "mc" "Don't you like it?"
    "s" "No, I love it"
    "s" "I just"
    "s" "Why did you spend so much money on a present for me?"
    "mc" "Because you're my best friend"
    "mc" "You've been helping me all this time"
    "mc" "Especially over the last couple weeks"
    "s" "You"
    "s" "You're impossible"
    "mc" "No, I'm highly improbable"
    "s" "Don't you start on that"
    "mc" "Hehe"
    "mc" "Oh, I'm being called for dinner"
    "mc" "I'll flash you later"
    "s" "You mean morse code, right?"

    time day 10 minute 42
    "s" "Right?"

    time day 14 hour 13 minute 12
    "s" "Lunch?"
    "mc" "Way ahead of you"
    "s" "Sweet"

    time day 17 hour 15 minute 22
    "mc" "I'm gonna head to the park, wanna come?"
    "s" "Sure"
    "s" "It'll be good to stretch my legs between all these exams"
    "mc" "Exactly"
    "mc" "Usual place?"
    "s" "Yep, be there shortly"

    time day 21 hour 8 minute 3
    "s" "I'm gonna make something cool for dinner, wanna come over and help?"
    "mc" "Hell yeah"
    "s" "Sweet, let's do it"
    "s" "Gonna need... I dunno, let's make a list and go shopping"
    "mc" "You haven't decided yet?"
    "s" "Nah, that's half the fun"
    "mc" "You might be right haha"
    "s" "Always am"
    "mc" "True true!"
    "s" "Then yeah, let's make it a date"
    "mc" "Yeah"

    time minute 51
    "s" "You don't have to"
    "s" "Never mind"
    "mc" "What?"
    "s" "Just forget it"
    "mc" "What?"
    "s" "Just drop it, it's fine"
    "mc" "It's clearly not fine"
    "s" "Yeah"
    "mc" "So tell me"
    "s" "Just"
    "s" "Be more confident in yourself, okay?"
    "mc" "Me?"
    "s" "Yeah"
    "s" "You're fantastic, so when you put yourself down, or say something mean toward yourself"
    "s" "I just don't want you to feel that way"
    "mc" "Yeah"
    "s" "I'll see you this afternoon when we go shopping, okay?"
    "mc" "Sure"

    time day 30 hour 11 minute 12
    "mc" "Hey, wanna get ice cream?"
    "s" "Hell yeah"
    "mc" "I'll pay for it if you can guess what flavour I'm thinking"
    "s" "Strawberry"
    "mc" "How"
    "s" "I'm psychic"
    "s" "We've had this conversation many times"
    "mc" "Shaddup"
    "s" "Ehe~"
    "mc" "I'll pick you up in five"

    time month 4 day 4 hour 7 minute 0
    "mc" "Guess what today is"
    "s" "April Day!"
    "mc" "Hell yeah it is"
    "s" "So we gonna party like it's April?"
    "mc" "Sure are!"
    "s" "What's on the agenda?"
    "mc" "After school, we go to the arcade"
    "s" "Good good"
    "mc" "Then we go and get a new anime"
    "s" "Yeah?"
    "mc" "And we watch it all the way through!"
    "s" "Yeah!"
    "s" "And because it's April Day, no-one can tell us what to do!"
    "mc" "Yeah!"
    "mc" "April Day!"
    "s" "Go April Day!"

    time day 7 hour 16 minute 41
    "s" "Hey, I forgot, Mom wanted me to tell you that she's making stew tonight!"
    "mc" "Fuck yeah!"
    "mc" "I mean"
    "mc" "Right, I'll be there"
    "s" "Ehe~"

    time day 10 hour 10 minute 31
    "mc" "Booooooooooored"
    "s" "Well that's no excuse to distract me"
    "s" "Kidding, kidding"
    "s" "Can't wait for lunch"
    "mc" "Same"
    "mc" "I'm just like"
    "mc" "Why do I have to learn basic mathematics again"
    "s" "To reinforce it for people who don't get it"
    "mc" "Who doesn't get it at this point?"
    "s" "Uhh"
    "mc" "Oh"
    "mc" "Sorry"
    "s" "Nah, it's cool"
    "s" "Oh, you know what?"
    "s" "Miss Smartypants can teach me"
    "mc" "Oooh"
    "mc" "Yeah, I totally could!"
    "mc" "Wait"
    "mc" "You were insulting me"
    "s" "What? Me? Never"
    "mc" "Yeah yeah"
    "mc" "Just remember, I have the lunches today"
    "s" "Nooooo"
    "s" "Not my food!"
    "mc" "Mwahahaha"
    "mc" "You better be nice then"
    "s" "I'll be nice, I promise!"
    "mc" "I'm gonna hold you to that"
    "s" "Melly, please, not my foooood"
    "mc" "Alright, alright. I'm not that mean"
    "s" "Yess, victory"
    "mc" "Oiii"
    "s" "Kidding! I promise I won't be mean"
    "mc" "You better"
    "s" "Ehe!"
    "mc" "I'll chat with you over lunch"
    "s" "I'll come stalk your classroom until you finish"
    "s" "You won't know where I am until I pop out and scare you!"
    "mc" "Maybe I'm hungry enough to eat two serves today..."
    "s" "Nooooooo"
    "s" "Meanie"
    "mc" "Hahaha"
    "mc" "I'll see you soon"

    time day 11 hour 16 minute 58
    "s" "Wanna go to the beach this weekend?"
    "mc" "For sure"
    "s" "Cool. Saturday sound good?"
    "mc" "Hell yeah"
    "s" "Let's do it then"

    time day 13 hour 10 minute 4
    "s" "I'll meet you down there"
    "mc" "Sounds good"

    time hour 18 minute 21
    "s" "Melly?"
    "s" "Where'd you go?"

    time minute 42
    "s" "C'mon, it's after sundown, I need to get home"

    time minute 58
    "s" "Mel, it's not funny anymore"

    time hour 19 minute 33
    "s" "Mel?"

    time day 14 hour 4 minute 23
    "s" "Melly, I'm really worried"
    "s" "Talk to me when you get up, okay?"
    "s" "I don't even know if you made it home safe"
    "s" "Okay?"

    time hour 7 minute 44
    "s" "I know you're awake"
    "s" "Please, talk to me"
    "s" "I'm not upset or anything"
    "s" "I just need to know that you're okay"

    time hour 11 minute 57
    "s" "Melly, I'm not angry"
    "s" "I knocked on your door, and you didn't answer"
    "s" "No-one did"
    "s" "What's going on?"
    "s" "Talk to me!"
    "s" "Melly, please, let me know you're okay!"

    time hour 16 minute 41
    "s" "Mel"
    "s" "Do you want me to be upset? Is that it?"
    "s" "Because even if you do, I'm not"
    "s" "It happens. We make stupid mistakes sometimes"
    "s" "But that wasn't- You didn't-"
    "s" "Just talk to me, please"
    "s" "What do I have to do?"
    "s" "I've tried everything"
    "s" "Just"
    "s" "Please talk to me"

    time day 15 hour 7 minute 0
    "s" "I take it we aren't walking to school together?"

    time hour 14 minute 23
    "s" "Well, considering you aren't here, we probably aren't walking home together either"

    time day 17 hour 3 minute 32
    "s" "I'm sorry, I overreacted"
    "s" "I didn't want to blow up at your phone like that a couple days ago"
    "s" "But I'm worried"
    "s" "I haven't seen or heard from you since it happened"
    "s" "But I'm not mad"
    "s" "Not at all"
    "s" "I forgive you, okay?"
    "s" "Just"
    "s" "What can I do to make you come back to me?"
    "s" "Melody, please"
    "s" "Don't leave me hanging"

    time day 21 hour 16 minute 43
    "s" "I get it"
    "s" "I'll give you some space for a while"
    "s" "I'll be here, okay?"

    time month 8 day 30 hour 0 minute 0
    "s" "Happy birthday, Melly"
    "s" "I hope you've been doing well"
    "s" "If you need anything, I'm right here, okay?"